### ISSUE TITLE
文档示例中‘import ('bmap-draw')’存在红线提示:找不到声明文件

### ISSUE THREAD

**Issue by gensuineixin** [yue1123/vue3-baidu-map-gl#100]
import('bmap-draw').then(({ DrawScene, DistanceMeasure, AreaMeasure }) 红线提示为：Could not find a declaration file for module 'bmap-draw'.  'd:/***/node_modules/bmap-draw/dist/bmap-draw.min.js' implicitly has an 'any' type.
![新建位图图像](https://github.com/user-attachments/assets/5b974e79-509e-4c30-a4af-9eadc837eb48)

**Comment by yue1123** [comment]
需要在 d.ts 中添加定义，参考文档的[dts](https://github.com/yue1123/vue3-baidu-map-gl/blob/main/docs/env.d.ts)文件
```ts
declare module 'bmap-draw'
```

**Comment by gensuineixin** [comment]
根据该方法，问题已解决。感谢。
