### ISSUE TITLE
离线地图怎么弄啊，文档也没有写

### ISSUE THREAD

**Issue by hecongyuan** [yue1123/vue3-baidu-map-gl#104]
离线地图怎么弄啊，文档也没有写，这个组件不维护了吗

**Comment by yue1123** [comment]
自建sdk链接，通过apiUrl自定义组件库sdk请求地址，这个文档有写。离线地图sdk怎么弄，网上搜一堆。

**Comment by hecongyuan** [comment]
sdk没太懂哎，可以给个联系方式吗，我们给你捐助
