### ISSUE TITLE
BInfoWindow BInfoWindow title 属性 偶尔出现无法更新的问题

### ISSUE THREAD

**Issue by huxiguo** [yue1123/vue3-baidu-map-gl#105]
![Snipaste_2024-10-19_10-44-17](https://github.com/user-attachments/assets/1c29ff6d-c214-4834-b54c-7a1792112213)
![Snipaste_2024-10-19_10-44-29](https://github.com/user-attachments/assets/bf23233a-c331-4be0-956b-20f10d23682d)

title 属性的值和下面的一致，但是下面出现了，上面却是undefined

**Comment by yue1123** [comment]
能否提供下最小复现demo，便于我修复这个问题
