### ISSUE TITLE
在加载百度个性化地图时，会出现白块现象，

### ISSUE THREAD

**Issue by zhaodianlong** [yue1123/vue3-baidu-map-gl#108]
查看了 源代码  也是用了setMapStyleV2 方法设置的 mapStyleId
![image](https://github.com/user-attachments/assets/d3bc1f69-dcbc-45ef-93e6-e172dc42bdd2)

有什么解决方法么

**Comment by yue1123** [comment]
这个应该是地图 api 本身的 bug，反馈给百度地图吧
