### ISSUE TITLE
center的双向绑定

### ISSUE THREAD

**Issue by Diaosi1111** [yue1123/vue3-baidu-map-gl#11]
我的用ref双向绑定好像不行

**Comment by yue1123** [comment]
哪一个组件?顺便贴上你的代码,我看看

**Comment by Diaosi1111** [comment]
<template>
    <input v-model="mapCenter.lng" type="number">
    <input v-model="mapCenter.lat" type="number">
    <input v-model="zoom" type="number">
    <Map ak="" :mapType="MapType.normal" height="100%" :enable-keyboard="false" enableDragging :minZoom="10" :center="mapCenter"
        @moving="syncCenterAndZoom" @moveend="syncCenterAndZoom" @zoomend="syncCenterAndZoom" ></Map>

</template>
  
<script setup lang="ts">
import { watchEffect, ref } from 'vue';
import { Point } from "./point";
import Marker from './Marker.vue';
import { Map, Control, Scale, Zoom, } from 'vue3-baidu-map-gl'


enum MapType {
    normal = "BMAP_NORMAL_MAP",
    earth = "BMAP_EARTH_MAP"
}
const mapType = ref(MapType.normal);
const mapSetting = ref({ enableDragging: true, enableInertialDragging: true, enableScrollWheelZoom: false, enableContinuousZoom: true, enableResizeOnCenter: true, enableDoubleClickZoom: false, enableKeyboard: true, enablePinchToZoom: true, enableAutoResize: true });

const mapCenter = ref({ lat: 38, lng: 117 });
const zoom = ref(15);


/**
 * 切换地图中心到指定位置
 * @param lat 
 * @param lng 
 */
const changeCenter = (lat: number, lng: number) => {
    mapCenter.value.lat = lat;
    mapCenter.value.lng = lng;
    console.debug("切换到坐标lat:", lat, " lng:", lng);
}
defineExpose({ changeCenter })

const handler = ({ BMap, map }) => {
    console.log(BMap, map);
    mapCenter.value.lng = 116.404;
    mapCenter.value.lat = 39.915;
    zoom.value = 15;
};

const syncCenterAndZoom = (e) => {
    const { lng, lat } = e.target.getCenter();
    zoom.value = e.target.getZoom();
    nextTick(() => {
        mapCenter.value.lng = lng;
        mapCenter.value.lat = lat;
    })
};

watchEffect(() => {
    console.log("===>", mapCenter.value)
})


defineProps<{ pointArr: Point[] }>()

</script>

**Comment by yue1123** [comment]
更新 0.0.7 试试

**Comment by Diaosi1111** [comment]
相当卡，拖动之后会出现input框里数据不停变化然后地图卡住的情况
```vue
<template>
    <input v-model="mapCenter.lng" type="number">
    <input v-model="mapCenter.lat" type="number">
    <input v-model="zoom" type="number">
    <Map ak="IDdZzXKwmNj1aHDPKa0uGuy1dhL88ZiB" :center="mapCenter" height="100%" :zoom="zoom" :minZoom="3"
        :mapType="mapType" :enableDragging="mapSetting.enableDragging"
        :enableInertialDragging="mapSetting.enableInertialDragging"
        :enableScrollWheelZoom="mapSetting.enableScrollWheelZoom"
        :enableContinuousZoom="mapSetting.enableContinuousZoom"
        :enableDoubleClickZoom="mapSetting.enableDoubleClickZoom" :enableKeyboard="mapSetting.enableKeyboard"
        :enablePinchToZoom="mapSetting.enablePinchToZoom" @moving="syncCenterAndZoom" @moveend="syncCenterAndZoom"
        @zoomend="syncCenterAndZoom">

        <!-- <Marker v-for="point in pointArr" :point="point"></Marker> -->

    </Map>
</template>
  
<script setup lang="ts">
import { watchEffect, ref, nextTick } from 'vue';
import { Point } from "./point";
import { Map, Control, Scale, Zoom, } from 'vue3-baidu-map-gl'

enum MapType {
    normal = "BMAP_NORMAL_MAP",
    earth = "BMAP_EARTH_MAP"
}
const mapType = ref(MapType.normal);
const mapSetting = ref({ enableDragging: true, enableInertialDragging: true, enableScrollWheelZoom: true, enableContinuousZoom: true, enableResizeOnCenter: true, enableDoubleClickZoom: false, enableKeyboard: true, enablePinchToZoom: true, enableAutoResize: true });

const mapCenter = ref({ lat: 38, lng: 117 });
const zoom = ref(15);


/**
 * 切换地图中心到指定位置
 * @param lat 
 * @param lng 
 */
const changeCenter = (lat: number, lng: number) => {
    mapCenter.value.lat = lat;
    mapCenter.value.lng = lng;
    console.debug("切换到坐标lat:", lat, " lng:", lng);
}
defineExpose({ changeCenter })

const syncCenterAndZoom = (e) => {
    const { lng, lat } = e.target.getCenter();
    zoom.value = e.target.getZoom();
    nextTick(() => {
        mapCenter.value.lng = lng;
        mapCenter.value.lat = lat;
    })
};

watchEffect(() => {
    console.log("===>", mapCenter.value)
})


defineProps<{ pointArr: Point[] }>()

</script>
```

**Comment by yue1123** [comment]
那是因为你监听了地图移动，改变了 mapCenter, 地图再次移动，又一次触发了你的监听，死循环了

**Comment by Diaosi1111** [comment]
> 那是因为你监听了地图移动，改变了 mapCenter, 地图再次移动，又一次触发了你的监听，死循环了

那不监听移动有办法改变mapCenter吗，把三个监听去了mapCenter不会跟着改变

**Comment by yue1123** [comment]
> > 那是因为你监听了地图移动，改变了 mapCenter, 地图再次移动，又一次触发了你的监听，死循环了
> 
> 那不监听移动有办法改变mapCenter吗，把三个监听去了mapCenter不会跟着改变

你要的效果是 input 输入框显示实时的 mapCenter，同时input 输入在地图中响应吗

**Comment by Diaosi1111** [comment]
> > > 那是因为你监听了地图移动，改变了 mapCenter, 地图再次移动，又一次触发了你的监听，死循环了
> > 
> > 
> > 那不监听移动有办法改变mapCenter吗，把三个监听去了mapCenter不会跟着改变
> 
> 你要的效果是 input 输入框显示实时的 mapCenter，同时input 输入在地图中响应吗

我的需求没那么高，主要是父组件可以改变mapcenter，现在问题是不监听地图移动,mapcenter不会改变，外部调用changeCenter()函数的时候地图是不会改变中心的，要手动通过input改变一次mapcenter后再通过changeCenter()才能实现中心的改变.(前后两次的center坐标一致，中间鼠标拖动改变中心，结果上地图不会切换过去)，我刚接触前端，这方面确实不太懂怎么去强制更新

**Comment by yue1123** [comment]
0.0.7 实时监听了 center, 你只要改变了 center 地图都会移动，你把你的其他逻辑都去掉，再从父组件调用一下 changeCenter 试试

**Comment by Diaosi1111** [comment]
> 0.0.7 实时监听了 center, 你只要改变了 center 地图都会移动，你把你的其他逻辑都去掉，再从父组件调用一下 changeCenter 试试

就是实际上center没有变，只是鼠标拖动的地图。第二次调用changecenter是想让点重新居中 。隔壁 vue-baidu-map-3x 边监听好像是可以的

**Comment by Diaosi1111** [comment]
还有个问题是好像没找到坐标转换的api

**Comment by yue1123** [comment]
> > 0.0.7 实时监听了 center, 你只要改变了 center 地图都会移动，你把你的其他逻辑都去掉，再从父组件调用一下 changeCenter 试试
> 
> 就是实际上center没有变，只是鼠标拖动的地图。第二次调用changecenter是想让点重新居中 。隔壁 vue-baidu-map-3x 边监听好像是可以的

换了和底层设置 center 的 api，更新 0.0.8 试试
如果你前后两次 center 一样，只是想回到中心点，你需要：
```js
mapCenter.value = JSON.parse(JSON.stringify(mapCenter.value))
```
这样才能触发 Vue 更新

**Comment by yue1123** [comment]
> 还有个问题是好像没找到坐标转换的api

监听initd事件，回调函数参数会带上地图实例，实例上可以调用相关方法
```html
<Map
  @initd="initdMap"
/>
```
```js
function initdMap(map) {
  console.log(map.pixelToPoint)
  console.log(map.pointToPixel)
  // ...
}
```
![image](https://user-images.githubusercontent.com/61490799/189603954-b49100b9-a082-4cb6-8dc8-75a992a35604.png)
