### ISSUE TITLE
BInfoWindow 标注点 点击两次 会多次才显示 窗口

### ISSUE THREAD

**Issue by gedaaxiba** [yue1123/vue3-baidu-map-gl#112]
点击 标注点 第一次 移动到标点位置     ，   再次点击标注点   才显示title  
   
![Snipaste_2024-11-07_22-21-42](https://github.com/user-attachments/assets/64bdb765-6765-46f3-8ce5-257e473196f3)
![Snipaste_2024-11-07_22-22-23](https://github.com/user-attachments/assets/33aab598-a796-4d7e-b181-ab74b0be43df)

             
                <BMap
                  v-if="isShow_has_data_Map"
                  :zoom="10"
                  enableScrollWheelZoom
                  mapStyleId="ee66c61531e8df3c2fd0374e96e58e81"
                  style="width: 100%; height: 100%;"
                >
                  <BNavigation3d :offset="{x:130,y:15}" />
                  <BScale />
                  <BCityList />
                  <BLocation />
                  <BZoom />
                  <BContextMenu :menuItems="list" />
                  <BMarker
                    v-for="(item,index) in deviceMapEffectScatterDataList"
                    :key="index"
                    :position="{ lat: item.lat, lng: item.lng }"
                    icon="location"
                    @click="() => handleClickMapBMarker(item)"
                  />
                  <BInfoWindow
                    v-model:show="mapInfoWindow.mapInfoWindowShow"
                    :offset="{x: 0,y: -10}"
                    :position="mapInfoWindow.position"
                    :title="mapInfoWindow.title"
                    enableAutoPan
                    enableCloseOnClick
                  />
                </BMap>
                <BMap
                  v-else
                  :menuItems="list"
                  :zoom="10"
                  enableScrollWheelZoom
                  mapStyleId="ee66c61531e8df3c2fd0374e96e58e81"
                  style="width: 100%; height: 100%;"
                />
                
![Snipaste_2024-11-07_22-17-53](https://github.com/user-attachments/assets/e50bb9d1-079f-4d29-a21d-c420319a6a92)

![Snipaste_2024-11-07_22-17-16](https://github.com/user-attachments/assets/6b5a2c12-b9b4-44e7-88d8-381ac4a4d3ce)

![Snipaste_2024-11-07_22-19-05](https://github.com/user-attachments/assets/ccc46cb4-ed59-4025-9015-7615de20fee5)

**Comment by yue1123** [comment]
能否提供下完整代码或者在线 [playground](https://play.vuejs.org/#eNqtV+tr3EYQ/1e2F0IcsHR63Lt2sC1cx40fqX3QEg6MTtq725xOEtLqHnEMhX4Obb8laaD0SymUhnwsbZP+M3FC/4vO7Ep3ukccFxobeXb2N6+d2ZnNeWE7DNVhQguNwgang9CzOb3T8gnZcNlQEEB+oijk7Z9/v3/25vKPny9fvLr84c3ly6fvX39PFCXD7BzaIRkxl/c2WwVd0262CqRHWbfH5XrYA4bdh0XfHO41vzhtH47uub2v2Gf39qK90/4jr988DWt7SQg46tttj546UeB5X/Yo9R4EwYBEtAPiAxsQ0ighDYf6nEbA9gLH5izw1TBgPiePH5PEd2mH+dQFhVvMZ9wFWJdyWDZASXMSUqkOqVYhDQRDEdYaQacTU/T+nIwbxDDWyaRBShq5AAXFHNpifHLAYr4koQkJY1ni1LE9Smzf6QXo+s7h9v2z7SPr7vHJ2c5xs3l8eHayv3e3uSB1ZA9ZV8RoutcSXvBHl/7oq0IIfA5nvVpr8/j+h1TOh+h4dhzDlpPEPBgojlSaO1kwFVOPOnwKlUuQ9e0BZgMohmmCv0NlELjUW5kioSoI8SzI0PYSFBUuHx2fHG4fnAEJ6HfPXv7z9XNZrxtFCf+4itPt5u7BwX5zN9Vy+eTXd09//K9adrdPmnczDS9evf/um3e//HT517crNGwU5SnM8lHMErKcopnYNSpgBl5dzLpmYuJafovLny3HYw7eUXFNZuKrM0uyO6e0uT+Dz6U7tP2p9BTO6RhzPlQYXmgWHwS2y/wuHtXL529fP3n7+2+qCscCwnllB6n8PtgHYerFNFfEKw4ta2iZpU/ypnKKoXdFfRqRRhjEDC0s9RPAgwEJm5O0WOR4NF8OMfjQp6d84mExxIHHoAEtA6zAE9m7oWn1eqczD2lIzHFoO9BcAKWptXlEh3ne1SoQkVdQXtj/QOdcQEVwXEk+eartOElkO5M8MJ+GuSki8gKTQY6UopwpcxhYxk7EQk482++CIR5DaUCtJijEBmEQcXKOvZ9ckE4EjfkWjKtbsy3UjCbWBYGtW1KiyUoy69Byle+j6b4snAyMGZW0TLigk5juRMEoplFWhoLNoTERsC4alJ/z0FTaNnMTBZqX0vVm/s4VsUSrxTwTpzHAWz7QMFRAnmxi+Gu3M9Y5geu5Pr1962Ra1kjuRlEQrUOV2TyJ4cw2V7i+5ieet07WbpPNO/IEwYwqGpgaUTh8SxQHmryYmk3bsPRmI435ztqthcZ7CwTg7oqcpvnFuwBkO3AnmbWoy/wG0T4FA4hR861EYtpB5NKoQfzApwCDkocsKTF7RKFxGeF4KrrQlHLCiqxemNoCTojLYqg76Hwdj0qOg3eoQW5UxD/BattOvxsF8HwAnXK30+mIrdB28ZgbpJIqhKsQI0JcHRpJ+WCsxD3bDUYNEnXbaxrBnyLRyzdvEz0cE3Ae/04DSGeicHw5yJU+Bgn34GmTO52FiDMHpx6jYV1LuQtnC25AxtIsFdYLslSxdNWHceDD21D4Bq1abMAFbUhvkQfliutWocd5GDeKRcf1QQxGNxtGqk950Q8HxS2AFaPE52xAFTcYbJmqqZagIcQ8z1ZpPFDaslhBSasgLllqBuZkNMQYKbzsIhpd1+yCWN70wtaHzbsTeKEwJxbcRbNxfwKNtq+6dFicA+a9n28I1/B9SUa6zMDVMToqLKABSN8FZG2xiSw86Vt8Ix52Z0/0ytwDHVdDRkc7wRinBRRsqQa/wMU5AiwsFViNB56P4wA9B8dHo5E6MtUg6hYNTdOKYAFHZWjzHsF33GFdrZWrtQoxDbVarpasimqYtXKNmKZaK5kGKRGzrJopVbVK8MBWTd2sQvWr9XLJJPBrANe0AKeVylVklGYwIFEsp0ZXqxUd1qkBs6bqJUPPHMDZImYrzk24TdO1kh3MDKLgFXPsEJjthOOLJcd/CDceNkSfaBWK+ZjBX7NsiS84R4yKWtbQTaJX1EpNr1lA1tVKtVoDrq7q1TrEIaK0AFEz4FVWIro+xQCZSQKZqpPqxffBUpZmIdbr9Y+GeHUohmGBSXGmhkGMOtHr6QrIqoXfEia1gp6JDR1g+LUMXW4AQ5/BkKxa+M0UpTBUj0b+93iwLOffHXBdeAz3pMO6Cy3OCQYh82h0LJ7p863O9rxg9Lng8SiRbwQh06NOfwX/YTyW9/w+DlXoNLmOwGEE4iMbt3dPj8SLeLoJ//NJ4FV51eYJhadlgj5K2A4EC27ncMLbfdGxYQI0490xp36cBYWOiuYh8KJDWVeEPnMXuue06Vz8CwIMInE=) 链接，只有截图我也看不出来是逻辑错误还是组件本身问题
