### ISSUE TITLE
img图片变化

### ISSUE THREAD

**Issue by zhongsdjn** [yue1123/vue3-baidu-map-gl#113]
**问题描述** vue3+Element plus在进入地图组件的页面时 会导致其它组件的图片变成很大

**复现步骤** 

**期望的表现**

**屏幕截图**
正常的
![e1](https://github.com/user-attachments/assets/cc60d43a-5b32-479d-a343-e2b6493fe238)
变化的
![e2](https://github.com/user-attachments/assets/08f45b01-5fd7-46d7-bf8a-fe6a4df952c2)

**电脑版本 (please complete the following information):**
windows10
- 系统: [e.g. iOS]
- 浏览器 [e.g. chrome, safari]
- all
- 版本 [e.g. 22]
2.6.1
**手机版本 (please complete the following information):**

- 手机型号: [e.g. iPhone6]
- 系统: [e.g. iOS8.1]
- 浏览器 [e.g. stock browser, safari]
- 版本 [e.g. 22]

**Comment by yue1123** [comment]
你 vue 代码中元素类名有 shadow 吧，和百度地图自己的 css匹配上了，换个名字就好了

**Comment by zhongsdjn** [comment]
是的，找到了

**Comment by Azir-11** [comment]
> 你 vue 代码中元素类名有 shadow 吧，和百度地图自己的 css匹配上了，换个名字就好了

这样的话大部分用原子css的项目都会出这个问题吧，要不要考虑一下全局给本项目的shadow等原子类名加上个特有前缀？

**Comment by yue1123** [comment]
> > 你 vue 代码中元素类名有 shadow 吧，和百度地图自己的 css匹配上了，换个名字就好了
> 
> 这样的话大部分用原子css的项目都会出这个问题吧，要不要考虑一下全局给本项目的shadow等原子类名加上个特有前缀？

百度地图api自己的css代码，改不了
