### ISSUE TITLE
clone 项目后直接运行 pnpm docs:dev 时报错

### ISSUE THREAD

**Issue by huguangju** [yue1123/vue3-baidu-map-gl#116]
**问题描述** 清楚描述问题.

10:21:03 [vitepress] Internal server error: Failed to resolve entry for package "vue3-baidu-map-gl". The package may have incorrect main/module/exports specified in its package.json.
  Plugin: vite:import-analysis
  File: xxx/vue/vue3-baidu-map-gl/docs/.vitepress/theme/index.ts

**复现步骤** 复现该问题的步骤:

1. clone 项目后直接运行 `pnpm docs:dev` 报上述错误
2. 运行 `pnpm dev` 生成 dist 目录后再运行 `pnpm docs:dev` 没问题

**期望的表现**

能直接运行 pnpm docs:dev` 命令，或在文档中注明。

**屏幕截图**

**电脑版本 (please complete the following information):**

- 系统: [e.g. iOS]
- 浏览器 [e.g. chrome, safari]
- 版本 [e.g. 22]

**手机版本 (please complete the following information):**

- 手机型号: [e.g. iPhone6]
- 系统: [e.g. iOS8.1]
- 浏览器 [e.g. stock browser, safari]
- 版本 [e.g. 22]

**Comment by yue1123** [comment]
需要先`pnpm build`构建项目或者运行 `pnpm dev`，后才能运行 `pnpm docs:dev`，会在文档中加以说明，感谢反馈
