### ISSUE TITLE
页面一直停在map-loading是啥情况

### ISSUE THREAD

**Issue by DonHaha233** [yue1123/vue3-baidu-map-gl#12]
就出现过一次，后续无法复现了

**Comment by DonHaha233** [comment]
![image](https://user-images.githubusercontent.com/73727285/198498526-8c3d85d7-6362-48ab-ba92-fc2c4edb0596.png)
就出现过一次，后续无法复现了

**Comment by yue1123** [comment]
刷新一下还会吗

**Comment by yue1123** [comment]
暂时先关掉，如果还有此问题，请重新打开
