### ISSUE TITLE
如何创建一个Point类型的点

### ISSUE THREAD

**Issue by DonHaha233** [yue1123/vue3-baidu-map-gl#13]
想问下作者有提供方法，创建Point类型的点么，在做跳转其他经纬度点的时候发现，不能通过new BMap.Point创建点，有提供类似方法吗？

**Comment by yue1123** [comment]
目前没有提供，后续可以考虑添加。你暂时可以通过访问 `window` 上的 `BMapGL.Point`来创建点

**Comment by yue1123** [comment]
BMapGL 需要在Map组件 initd 事件触发后才能访问
