### ISSUE TITLE
地图定位好了后，然后拖拽地图，怎么点击定位按钮 让地图移动到以定位为中心点的地方

### ISSUE THREAD

**Issue by a2734961** [yue1123/vue3-baidu-map-gl#14]
<img width="853" alt="image" src="https://user-images.githubusercontent.com/53285767/202175452-e3a4dd0f-2684-4ad2-acd1-9b23061807cf.png">

**Comment by yue1123** [comment]
升级到`0.0.34`，调用map组件的 resetCenter 方法，可以参考[useBrowserLocation文档实例代码](https://yue1123.github.io/vue3-baidu-map-gl/zh/hooks/useBrowserLocation#%E7%A4%BA%E4%BE%8B)

**Comment by a2734961** [comment]
> 升级到`0.0.34`，调用map组件的 resetCenter 方法，可以参考[useBrowserLocation文档实例代码](https://yue1123.github.io/vue3-baidu-map-gl/zh/hooks/useBrowserLocation#%E7%A4%BA%E4%BE%8B)

有没有 提供 可以 改变 center值， 移动地图的方法？
比如搜索我的某个marker标点，地图移动到相应的经纬，有办法吗？

**Comment by a2734961** [comment]
> 升级到`0.0.34`，调用map组件的 resetCenter 方法，可以参考[useBrowserLocation文档实例代码](https://yue1123.github.io/vue3-baidu-map-gl/zh/hooks/useBrowserLocation#%E7%A4%BA%E4%BE%8B)

ok。解决了，谢谢哥~

**Comment by a2734961** [comment]
> 升级到`0.0.34`，调用map组件的 resetCenter 方法，可以参考[useBrowserLocation文档实例代码](https://yue1123.github.io/vue3-baidu-map-gl/zh/hooks/useBrowserLocation#%E7%A4%BA%E4%BE%8B)

另外一个小问题。marker能控制层级吗。比如我的定位点 显示在前面，其他标记点在后面
<img width="259" alt="image" src="https://user-images.githubusercontent.com/53285767/202333093-75edde3d-8add-421c-9122-898591e63dff.png">

**Comment by a2734961** [comment]
> 升级到`0.0.34`，调用map组件的 resetCenter 方法，可以参考[useBrowserLocation文档实例代码](https://yue1123.github.io/vue3-baidu-map-gl/zh/hooks/useBrowserLocation#%E7%A4%BA%E4%BE%8B)

map的 height 能做成ref自适应的吗？ 根据交互需要变化！

**Comment by yue1123** [comment]
> > 升级到`0.0.34`，调用map组件的 resetCenter 方法，可以参考[useBrowserLocation文档实例代码](https://yue1123.github.io/vue3-baidu-map-gl/zh/hooks/useBrowserLocation#%E7%A4%BA%E4%BE%8B)
> 
> map的 height 能做成ref自适应的吗？ 根据交互需要变化！

hight 是个静态属性，你可以试试 css 的相对高度，比如`100%`、`100vh`

**Comment by yue1123** [comment]
> > 升级到`0.0.34`，调用map组件的 resetCenter 方法，可以参考[useBrowserLocation文档实例代码](https://yue1123.github.io/vue3-baidu-map-gl/zh/hooks/useBrowserLocation#%E7%A4%BA%E4%BE%8B)
> 
> 另外一个小问题。marker能控制层级吗。比如我的定位点 显示在前面，其他标记点在后面 <img alt="image" width="259" src="https://user-images.githubusercontent.com/53285767/202333093-75edde3d-8add-421c-9122-898591e63dff.png">

当前版本marker组件没有提供设置层级的 props，但是你可以监听@initd 事件，通过事件参数中的 marker 实例调用实例方法`setZIndex`，百度地图文档上写了有，我没试过，不知道行不行，你试试吧。下个版本吧层级属性加到 Props 里面
