### ISSUE TITLE
 大神，你的项目相当棒~奉上成品特来感谢~

### ISSUE THREAD

**Issue by a2734961** [yue1123/vue3-baidu-map-gl#15]
<img width="440" alt="image" src="https://user-images.githubusercontent.com/53285767/202656992-f1a5b89b-fe63-4e0b-b91d-5ee89717f8f9.png">

**Comment by yue1123** [comment]
哈哈，挺好的，star点起来🥳

**Comment by a2734961** [comment]
> 

ok ok

**Comment by yue1123** [comment]
感谢支持，这个 issue 就不关了，挂着当一个案例展示

**Comment by imaxing** [comment]
@yue1123 大佬 组件很好用
请问组件中的全景组件有没有想法独立出来一个包 感觉体验很好 :)

**Comment by yue1123** [comment]
> @yue1123 大佬 组件很好用
> 请问组件中的全景组件有没有想法独立出来一个包 感觉体验很好 :)

全景组件就是用的百度地图SDK的api啊，代码很简单，没有独立出来一个包的必要吧。这个组件库组件都是模块分包，按需加载的，只用这两个组件也不会有冗余的代码
