### ISSUE TITLE
Uncaught ReferenceError: md5 is not defined

### ISSUE THREAD

**Issue by shuaibishun** [yue1123/vue3-baidu-map-gl#18]
nuxt3中

**Comment by yue1123** [comment]
能提供一下控制台报错调用栈截图吗

**Comment by imziwen** [comment]
![md5](https://user-images.githubusercontent.com/14174105/226882068-9c8667d1-3e8d-4d08-9b23-bd0dd5bc4470.png)

老哥，nuxt3中报错，md5 is not defined

**Comment by samsonsunxiao** [comment]
遇到同样问题，请问解决了吗？
