### ISSUE TITLE
获取定位控件控制台报错：跨源读取阻止(CORB)功能阻止了 MIME 类型为 application/json

### ISSUE THREAD

**Issue by weijiazhen** [yue1123/vue3-baidu-map-gl#19]
![image](https://user-images.githubusercontent.com/51360961/206945166-aeadedab-257c-4e55-922f-01c996d5d222.png)

获取定位控件控制台报错：跨源读取阻止(CORB)功能阻止了 MIME 类型为 application/json

**Comment by weijiazhen** [comment]
> ![image](https://user-images.githubusercontent.com/51360961/206945166-aeadedab-257c-4e55-922f-01c996d5d222.png)
> 
> 获取定位控件控制台报错：跨源读取阻止(CORB)功能阻止了 MIME 类型为 application/json

应该是获取百度api返回的格式改成json类型就行了

**Comment by yue1123** [comment]
这个应该是百度地图api的问题，我自己也遇到了，没找到解决办法。你解决了吗，返回格式不是不能改嘛

**Comment by weijiazhen** [comment]
我后面用Bmap实例自己调百度api，参数加上output=json就可以了
