### ISSUE TITLE
feat: point-collection 

### ISSUE THREAD

**Issue by YonJey** [yue1123/vue3-baidu-map-gl#20]
vue-baidu-map 这个库有个 BmPointCollection 海量点，我的项目中也需要这个，目前想把项目转为vue3，但是在您的文档中未发现这个功能，还是说可以换其他的方式实现 BmPointCollection ?

**Comment by yue1123** [comment]
baidu map gl API没有提供这个功能，你可以循环渲染Marker组件来实现
