### ISSUE TITLE
zoomend无法对zoom进行监听

### ISSUE THREAD

**Issue by 39499740** [yue1123/vue3-baidu-map-gl#22]
我这边会通过代码的方式修改地图的zoom，比如
```
zoom.value = 18
//或者
    map.value.getMapInstance().setZoom(18)
```

假如我目前的zoom是10，点击按钮后将zoom修改为18，地图可以正常修改zoom，但是zoomend中无法监听到18的状态。
```
    console.log(map.value.getMapInstance().getZoom())

```

目前我想实现当zoom动画结束后，如果zoom大于12，则tilt为45，否则为0
目前由于无法监听zoom，没法实现这个效果。

请问这是BUG还是我的代码有问题？

**Comment by yue1123** [comment]
这个问题应该是地图api的 bug, zoomend 提前触发了，实际上zoom的动画还没有结束，动画结束了获取 zoom 才是最新的值。
你尝试把代码放到一个延时器里面执行，应该就可以获取到了
```js
setTimeout(() => {
   console.log(map.value.getMapInstance().getZoom())
},1000)
```

**Comment by 39499740** [comment]
经过测试发现，如果使用centerAndZoom来进行缩放，就可以在缩放完成后，从zoomend中获取通知。如果直接设定zoom，则会提前触发。算是找到了解决办法

**Comment by yue1123** [comment]
有点坑，感觉这是个bug
