### ISSUE TITLE
点击标注如何去显示该标注的信息

### ISSUE THREAD

**Issue by lvhaidong-9587** [yue1123/vue3-baidu-map-gl#23]
最近在给地图上添加标注，标注的坐标都为动态数目也不确定，现在标注搞完了但如何给这些标注添加信息窗口呢，类似于https://lbs.baidu.com/jsdemo.htm#webgl1_4 这样的，点标注信息出现

**Comment by lvhaidong-9587** [comment]
部分代码：
  <Marker :position="item" icon="loc_blue" v-for="(item,i) of table" :key="i"  v-on:click="divover(item)"
                    enableClicking/>
            <InfoWindow  v-model="show" :position="item" title="停车场信息" enableAutoPan enableCloseOnClick>
               {{title}}
            </InfoWindow>

<script setup>
import {Map, Marker, InfoWindow} from 'vue3-baidu-map-gl'
let table = [
{ lat: 115404, lng: 39.925 },
{ lat: 117.404, lng: 39.925 },
{ lat: 118.404, lng: 39.925 },
]
</script>

<script>
 divover:function (item){
      this.item = item;
      this.show = true;
      this.title = "地址：北京市东城区王府井大街88号乐天银泰百货八层";
    },
</script>

**Comment by yue1123** [comment]
整理一下数据结构，给每一个 marker 渲染一个相同位置的 InfoWindow，改变 show 的值显示
```html
<template>
  <Map enableScrollWheelZoom v-bind="$attrs" :center="{ lat: 39.915185, lng: 116.400901 }" :zoom="16">
    <template :key="i" v-for="(item, i) of table">
      <Marker :position="item.position" icon="blue1" v-on:click="item.show = true" enableClicking />
      <InfoWindow v-model="item.show" :position="item.position" title="停车场信息" enableAutoPan enableCloseOnClick>
        {{ item.title }}
      </InfoWindow>
    </template>
  </Map>
</template>

<script setup>
  import { ref } from 'vue'
  import { Map, Marker, InfoWindow } from 'vue3-baidu-map-gl'
  let table = ref([
    {
      position: { lat: 39.915185, lng: 116.400901 },
      title: '地址：北京市东城区王府井大街88号乐天银泰百货八层',
      show: false
    },
    {
      position: { lat: 39.915185, lng: 116.600901 },
      title: '地址：北京市东城区王府井大街88号乐天银泰百货八层123',
      show: false
    }
  ])
</script>

```
