### ISSUE TITLE
和elementPlus同时使用

### ISSUE THREAD

**Issue by ufxelv80** [yue1123/vue3-baidu-map-gl#24]
和elementPlus同时使用时控制台会出现一堆警告，如果项目部引入地图或者不适用ElementPlus时就不会出现警告

**Comment by yue1123** [comment]
可以给个警告的截图吗

**Comment by ufxelv80** [comment]
![QQ截图20230306202621](https://user-images.githubusercontent.com/120778315/223110095-26e2c3ab-9262-4f65-bb7a-ccfdf6e6a2dc.png)

或者不全局注册，按需引入的时候也不会有警告

**Comment by yue1123** [comment]
这就是必传的 props 没有被传入的警告啊，Label 在地图上有正确的渲染没？3,4警告感觉是你没把 Label 组件放到 Map 组件中

**Comment by ufxelv80** [comment]
但是Label组件我没有用，页面上我就是只用了基础的Map

**Comment by yue1123** [comment]
升级 1.1.4 试试

**Comment by ufxelv80** [comment]
升级了也还是一样的
![QQ截图20230307185848](https://user-images.githubusercontent.com/120778315/223403405-7b510e4a-b6e7-46fb-b1b2-c2b2ceb1353d.png)

**Comment by yue1123** [comment]
定位到问题了，和element-plus 表单内部label组件冲突了，2.0.0 解决了这个问题，但是所有组件都必须加前缀`B`，你升级一下试试

**Comment by ufxelv80** [comment]
好的，我升级试一下

**Comment by ufxelv80** [comment]
可以了，谢谢！！！
![QQ截图20230311110832](https://user-images.githubusercontent.com/120778315/224462969-c140ec10-e776-47a6-9fea-ec0724b72f02.png)

**Comment by yue1123** [comment]
ok，客气了
