### ISSUE TITLE
[.WebGL-0x11c08b8a300] GL_INVALID_FRAMEBUFFER_OPERATION

### ISSUE THREAD

**Issue by a2734961** [yue1123/vue3-baidu-map-gl#25]
[.WebGL-0x11c08b8a300] GL_INVALID_FRAMEBUFFER_OPERATION: Framebuffer is incomplete: Attachment has zero size.
:5175/app-dev/#/page/drugstore:1 [.WebGL-0x11c08b8a300] GL_INVALID_FRAMEBUFFER_OPERATION: Draw framebuffer is incomplete

console 里 报了一长串的这个错误，你知道是怎么回事吗，用的router，进到地图页面就会出现这个，刷新地图页面，不会有！

**Comment by a2734961** [comment]
问题已经得到解决 和vue3 使用<transition>组件有关~

**Comment by yue1123** [comment]
好的
