### ISSUE TITLE
地图重新绘制（ref, computed）

### ISSUE THREAD

**Issue by ipaddicting** [yue1123/vue3-baidu-map-gl#26]
坐标点参数（比如 <Map :center="some point">, 或 <Polyline :path="some points">）发生变化的时候，地图重新绘制。

**Comment by yue1123** [comment]
center 坐标点吗

**Comment by ipaddicting** [comment]
> 

嗯，就我的使用场景来说：center坐标点是其中一个变量；另外一个变量是polyline的坐标点集合。

目前是用 vue component key 的方式来实现 map 组件的动态刷新。

**Comment by yue1123** [comment]
map 组件的center本身就是一个动态props啊，只要改变了地图就会实时更新，没更新的话，你确认下你的变量是否是ref定义的

**Comment by ipaddicting** [comment]
谢谢提醒，使用pinia的storeToRefs就好了。

**Comment by yue1123** [comment]
ok
