### ISSUE TITLE
自定义加载如何实现？

### ISSUE THREAD

**Issue by freehzw** [yue1123/vue3-baidu-map-gl#28]
按照[文档说明](https://yue1123.github.io/vue3-baidu-map-gl/zh-CN/components/map)，我的代码大致如下：

```
<BMap :heading="mapOpts.heading" :tilt="mapOpts.tilt" :center="center" @initd="initd">

  <template #loading="{ isLoading }">
    <a-spin v-if="isLoading"></a-spin>
  </template>
</BMap>

const isLoading = ref(false);

function initd(){
isLoading.value = true;
}
```

不能成功。报错：`runtime-dom.esm-bundler.js:10 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'insertBefore')`。请指教。

**Comment by freehzw** [comment]
谢谢。可以的。不过，虽然我的地图风格是黑色，在加载结束之前，还是有一段时间的白屏，有什么方法可以解决？

**Comment by yue1123** [comment]
覆盖一下原有的css背景颜色就好了：
```css
.baidu-map-container{
  background: #333 !import;
}
```

**Comment by freehzw** [comment]
谢谢。有效果，白屏时间短了，就是加载结束前一刻还有白屏，我先仔细检查下自己的css有没有问题。

**Comment by yue1123** [comment]
好的，有问题再打开这个issue
