### ISSUE TITLE
能增加地址搜索功能吗？

### ISSUE THREAD

**Issue by freehzw** [yue1123/vue3-baidu-map-gl#29]
现在有这个组件吗？就是搜索地址，在地图出现相应的点，原生地图的功能。

**Comment by yue1123** [comment]
目前没有，挖个坑，下个版本可能会有。目前只能用原生api自定义实现

**Comment by mamba-in** [comment]
> 目前没有，挖个坑，下个版本可能会有。目前只能用原生api自定义实现

我现在也有搜索的需求，请问作者大佬，使用您这个组件库还能再用原生api吗，怎么在页面创建地图实例

**Comment by mamba-in** [comment]
> 

好的，多谢

**Comment by mamba-in** [comment]
> > > 目前没有，挖个坑，下个版本可能会有。目前只能用原生api自定义实现
> > 
> > 
> > 我现在也有搜索的需求，请问作者大佬，使用您这个组件库还能再用原生api吗，怎么在页面创建地图实例
> 
> @mamba-in 可以的，任意一个组件的initd事件就可以获取到原生Api。可以参考下这个例子：https://yue1123.github.io/vue3-baidu-map-gl/zh-CN/expand/bmap-draw

好的，感谢。期待咱们的新版本！

**Comment by mianba** [comment]
bmap-draw 我看不支持搜索功能呢，期待新版本
