### ISSUE TITLE
地图怎么只展示某个城市，屏蔽掉其他城市？

### ISSUE THREAD

**Issue by bluemoon-i** [yue1123/vue3-baidu-map-gl#31]
1.地图怎么只展示某个城市，屏蔽掉其他城市？
2.城市里的区县怎么分别用不同的颜色？

**Comment by yue1123** [comment]
屏蔽其他城市现版本还没有提供相关组件，你可以自己用MapMask api来实现，行政区不同颜色可以试试行政区图层组件

**Comment by bluemoon-i** [comment]
好的，那怎么在您的地图组件中使用MapMask api来实现呢？搜了很久，不知道怎么实现

**Comment by yue1123** [comment]
监听Map组件的Initd事件，然后就可以用BMapGL.MapMask api了

**Comment by yue1123** [comment]
具体api怎么用，你要看下百度官方的文档

**Comment by bluemoon-i** [comment]
作者您好，我在本地测试了dev分支的MapMask组件，使用是没有问题的，辛苦了。

**Comment by yue1123** [comment]
晚上我会发一个版本，到时候你用正式版吧
