### ISSUE TITLE
一个组件中使用两个BMap组件，BMap组件都有BCityList组件，会导致第二个BCityList失效

### ISSUE THREAD

**Issue by yi0708** [yue1123/vue3-baidu-map-gl#32]
vue3 一个组件中使用两个BMap组件，BMap组件都有BCityList组件，会导致第二个BCityList失效，只有第一个BCityList组件才正常，第二个BCityList能显示，但是操作不了

**Comment by yue1123** [comment]
你试下百度官方demo会不会有这问题

**Comment by yi0708** [comment]
官方demo也是这样
