### ISSUE TITLE
BInfoWindow组件报错

### ISSUE THREAD

**Issue by zogwosh** [yue1123/vue3-baidu-map-gl#34]
报错信息
`runtime-core.esm-bundler.js:41  [Vue warn]: Unhandled error during execution of watcher callback 
  at <BInfoWindow modelValue=true onUpdate:modelValue=fn enableMaximize=""  ... > 
  at <BMap zoom=16 ak="cwHsf5i2fAQAlijOyELx5COtkFhItaSm" height="100vh"  ... > 
  at <App>
warn2 @ runtime-core.esm-bundler.js:41
runtime-core.esm-bundler.js:41  [Vue warn]: Unhandled error during execution of scheduler flush. This is likely a Vue internals bug. Please open an issue at https://new-issue.vuejs.org/?repo=vuejs/core 
  at <BInfoWindow modelValue=true onUpdate:modelValue=fn enableMaximize=""  ... > 
  at <BMap zoom=16 ak="cwHsf5i2fAQAlijOyELx5COtkFhItaSm" height="100vh"  ... > 
  at <App>
warn2 @ runtime-core.esm-bundler.js:41
Show 1 more frame
VM190:1  Uncaught (in promise) TypeError: Cannot read properties of null (reading 'config')
    at d2.setPosition (eval at run (getscript?type=webgl&v=1.0&ak=cwHsf5i2fAQAlijOyELx5COtkFhItaSm&services=&t=20230613170744:5:126869), <anonymous>:1:11263)
    at setPosition (index.vue.js?v=43191f0d:174:24)
    at index.vue.js?v=43191f0d:99:17
    at helper.js?v=43191f0d:9:13
    at callWithErrorHandling (runtime-core.esm-bundler.js:158:18)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:166:17)
    at job (runtime-core.esm-bundler.js:1756:9)
    at flushPreFlushCbs (runtime-core.esm-bundler.js:304:7)
    at updateComponentPreRender (runtime-core.esm-bundler.js:5832:5)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5750:11)
client.ts:447 
        
        
        GET http://localhost:5173/src/assets/main.css?t=1687321637195 net::ERR_ABORTED 404 (Not Found)
fetchUpdate @ client.ts:447
(anonymous) @ client.ts:159
handleMessage @ client.ts:157
(anonymous) @ client.ts:90
Show 4 more frames
client.ts:114  [hmr] Failed to reload /src/assets/main.css. This could be due to syntax errors or importing non-existent modules. (see errors above)
warnFailedFetch @ client.ts:114
fetchUpdate @ client.ts:453
await in fetchUpdate (async)
(anonymous) @ client.ts:159
handleMessage @ client.ts:157
(anonymous) @ client.ts:90
Show 5 more frames
client.ts:447 
        
        
        GET http://localhost:5173/src/assets/main.css?t=1687321637196 net::ERR_ABORTED 404 (Not Found)
fetchUpdate @ client.ts:447
(anonymous) @ client.ts:159
handleMessage @ client.ts:157
(anonymous) @ client.ts:90
Show 4 more frames
client.ts:114  [hmr] Failed to reload /src/assets/main.css. This could be due to syntax errors or importing non-existent modules. (see errors above)`
目前我的临时解决方法是在BInfoWindow的setPosition中添加open()
复现demo
[vue-project.zip](https://github.com/yue1123/vue3-baidu-map-gl/files/11812232/vue-project.zip)

**Comment by yue1123** [comment]
你的需求应该和这个 https://github.com/yue1123/vue3-baidu-map-gl/issues/23 差不多，可以参考一下。这个问题后续我复现修复一下
