### ISSUE TITLE
引入项目之后，提示ERROR in ./node_modules/vue3-baidu-map-gl/types/index.d.ts

### ISSUE THREAD

**Issue by NJHSFNAK** [yue1123/vue3-baidu-map-gl#35]
node : v16.5.0
pnpm:  @v7.22.0
vue: 3.2.13
引入项目之后，在main.ts中引入vue3-baidu-map-gl，然后配置后，提示ERROR in ./node_modules/vue3-baidu-map-gl/types/index.d.ts。
报错提示内容
<img width="1107" alt="Snipaste_2023-06-21_17-26-11" src="https://github.com/yue1123/vue3-baidu-map-gl/assets/38530519/bd02ab6b-52ee-4dca-a17f-f4c3f6aa1a5b">

main.ts引入内容
![WX20230621-172747@2x](https://github.com/yue1123/vue3-baidu-map-gl/assets/38530519/0fbe59d4-d214-4099-920a-6709a5114a82)
请问一下，我是哪里没有配置吗

**Comment by yue1123** [comment]
webpack吗

**Comment by NJHSFNAK** [comment]
> webpack吗

是的，需要在webpack中配置什么吗

**Comment by yue1123** [comment]
是个 bug，之前一直是用 vite 测试的，vite 走的是 esm, webpack 走的是 cjs，cjs 没办法解析.d.ts，导致了你这个错误，我修一下发个版
