### ISSUE TITLE
我引用这个插件，但是一直报一个错，大佬有空帮忙看看吗？以下是代码和贴图

### ISSUE THREAD

**Issue by wxy-133** [yue1123/vue3-baidu-map-gl#38]
报错
![image](https://github.com/yue1123/vue3-baidu-map-gl/assets/59717929/aadff93d-c09f-480e-9fe7-3e4dab42c0e3)

代码
`  <BMap
                    enableScrollWheelZoom
                    ref="map"
                    :center="location.point || undefined"
                    @initd="get"
                  >
                    <template v-if="!isLoading">
                      <BMarker :position="location.point"></BMarker>
                    </template> </BMap>
。。。。。
import { BMap } from 'vue3-baidu-map-gl'
import { useIpLocation } from 'vue3-baidu-map-gl'
const isLoading = ref()
const map = ref()
const { get, location } = useIpLocation(() => {
  map.value.resetCenter()
})
。。。。
import { createApp } from 'vue'
import baiduMap from 'vue3-baidu-map-gl'
import App from './App.vue'
import router from './router'

import './assets/style/main.scss'
import { globalRegister } from '@/global/register'

const app = createApp(App)
globalRegister(app)
app.use(router)
app.use(baiduMap, {
  ak: 'b9ZvWgXRS45HNLXcAPPOGi0zG7fp7Mzc',
  plugins: ['TrackAnimation']
})
app.mount('#app')
`

**Comment by wxy-133** [comment]
`
 <BMap
                    enableScrollWheelZoom
                    ref="map"
                    :center="location.point || undefined"
                    @initd="get"
                  >
                    <template v-if="!isLoading">
                      <BMarker :position="location.point"></BMarker>
                    </template>
                  </BMap>
。。。。。
import { BMap } from 'vue3-baidu-map-gl'
import { useIpLocation } from 'vue3-baidu-map-gl'
const isLoading = ref()
const map = ref()
const { get, location } = useIpLocation(() => {
map.value.resetCenter()
})
。。。。
import { createApp } from 'vue'
import baiduMap from 'vue3-baidu-map-gl'
import App from './App.vue'
import router from './router'

import './assets/style/main.scss'
import { globalRegister } from '@/global/register'

const app = createApp(App)
globalRegister(app)
app.use(router)
app.use(baiduMap, {
ak: 'b9ZvWgXRS45HNLXcAPPOGi0zG7fp7Mzc',
plugins: ['TrackAnimation']
})
app.mount('#app')
`

**Comment by yue1123** [comment]
我这边使用你提供的代码没有复现，地图 sdk的原因。这个警告影响运行吗
