### ISSUE TITLE
移动端无法使用

### ISSUE THREAD

**Issue by flycran** [yue1123/vue3-baidu-map-gl#39]
<img width="1111" alt="image" src="https://github.com/yue1123/vue3-baidu-map-gl/assets/86134803/81a2ace4-1b0a-45d0-9462-1929b60f5049">
如图，包括真机也是同样的情况

**Comment by yue1123** [comment]
系统版本和浏览器版本是多少？你可以试一下文档上面的demo可以正常运行不，如果不行的话，可能是不兼容
