### ISSUE TITLE
必须使用pnpm吗？

### ISSUE THREAD

**Issue by seeseasonjack** [yue1123/vue3-baidu-map-gl#40]
npm ERR! vue3-baidu-map-gl@2.2.2 preinstall: `npx only-allow pnpm`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue3-baidu-map-gl@2.2.2 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by yue1123** [comment]
不会啊，这个只是限制参与这个项目开发的都必须使用pnpm，正常install不会限制。你是怎么触发的

**Comment by seeseasonjack** [comment]
npm install vue3-baidu-map-gl@latest --save  触发的

**Comment by seeseasonjack** [comment]
npm 9.5.1

**Comment by yue1123** [comment]
我一样的npm版本，没有触发这个报错，有点奇怪呢

**Comment by yue1123** [comment]
![IMG_7401](https://github.com/yue1123/vue3-baidu-map-gl/assets/61490799/843745f8-6283-488e-97c9-4044f56aaf84)

**Comment by seeseasonjack** [comment]
那有可能我的环境哪里不对，我再搞搞试试吧，谢谢

**Comment by E1FANG** [comment]
我也出现这个only-allow pnpm的问题了，用yarn安装之后没有写入packagejson里，手动加上就可以了

**Comment by yue1123** [comment]
> 我也出现这个only-allow pnpm的问题了，用yarn安装之后没有写入packagejson里，手动加上就可以了

emm，下个版本把这个去掉，按理说不应该出现这个问题，我也不知道为什么
