### ISSUE TITLE
使用mapvgl创建three.js图层报错

### ISSUE THREAD

**Issue by helloworld666** [yue1123/vue3-baidu-map-gl#43]
function handlePluginReady(map) {
    const threeLayer = new mapvgl.ThreeLayer();
}
执行上面函数，使用mapvgl，版本1.0.0-beta.185，创建three.js图层报错，错误如下：
[Vue3 BaiduMap GL/BMap]: plugins load error: TypeError: mapvgl.ThreeLayer is not a constructor

**Comment by yue1123** [comment]
确保插件资源地址是否正确，如果是正确的，在浏览器控制台看看有没有mapvgl

**Comment by yue1123** [comment]
https://yue1123.github.io/vue3-baidu-map-gl/zh-CN/expand/mapv#%E6%B8%B2%E6%9F%93-3d-%E6%A8%A1%E5%9E%8B

**Comment by helloworld666** [comment]
> 确保插件资源地址是否正确，如果是正确的，在浏览器控制台看看有没有mapvgl
感谢您的回复。mapvgl对象的调用是没问题的。我创建的mapvgl.ShapeLayer对象一切正常，其它相关的layer对象也都能正常调用，包括您下面链接例子中的layer对象创建也都没问题，就是无法创建ThreeLayer对象。

**Comment by yue1123** [comment]
threeLayers这个功能貌似要单独通过另一个包引入，具体你看下mapvgl官方文档吧
