### ISSUE TITLE
本地没问题，打包部署到linux 服务器  控制台报错

### ISSUE THREAD

**Issue by ufly-site** [yue1123/vue3-baidu-map-gl#44]
![image](https://github.com/yue1123/vue3-baidu-map-gl/assets/50296782/54a8ce48-9e05-459b-9444-cf843c02bc61)

**Comment by yue1123** [comment]
项目用到了预渲染或者 ssr 吗

**Comment by FizzlingFish** [comment]
我也是这个报错。。解决了吗楼主 @ufly-site

**Comment by FizzlingFish** [comment]
没用到预渲染或者 ssr

**Comment by FizzlingFish** [comment]
应该是这部分
![image](https://github.com/yue1123/vue3-baidu-map-gl/assets/21310612/857d5960-1040-4e48-a7e6-173c99651f2e)
![image](https://github.com/yue1123/vue3-baidu-map-gl/assets/21310612/38fa90da-4be0-431c-8d11-3777ef28b0b9)
![image](https://github.com/yue1123/vue3-baidu-map-gl/assets/21310612/83cca2d1-f54c-49fe-96c5-e6081c4d6796)

**Comment by yue1123** [comment]
get ~~
