### ISSUE TITLE
与electron 27.0 集成有问题

### ISSUE THREAD

**Issue by Moon1102** [yue1123/vue3-baidu-map-gl#49]
[Vue3 BaiduMap GL/BMap]: aF is not defined

**Comment by yue1123** [comment]
> 基础的地图和控件还是能正常显示的 ，使用https://yue1123.github.io/vue3-baidu-map-gl/zh-CN/expand/mapv 示例代码 没有反应，没有额外的报错。 可能是mapvgl本身的问题

可以提供一下最小复现 demo 或者报错堆栈和代码位置的截图吗，我看下是不是
