### ISSUE TITLE
Mapvgl 版本过低

### ISSUE THREAD

**Issue by Hi-Alan** [yue1123/vue3-baidu-map-gl#52]
发现 Mapvgl@1.0.0-beta.159 一个 bug: TextLayer 的文字大小设置无效;
使用 mapvgl@1.0.0-beta.186 则没有这个问题

`https://unpkg.com/mapvgl@1.0.0-beta.186/dist/mapvgl.min.js`

**Comment by yue1123** [comment]
你是通过插件的形式使用的吗？如果是的话，你可以自定义一些Mapvgl 资源地址
```html
<BMap
  :plugins=['Mapvgl']
  :pluginsSourceLink="{
    Mapvgl: 'https://unpkg.com/mapvgl@1.0.0-beta.186/dist/mapvgl.min.js'
  }"
/>
```
