### ISSUE TITLE
useViewAnimation  引入执行开始报错

### ISSUE THREAD

**Issue by Rickmoti** [yue1123/vue3-baidu-map-gl#54]
![image](https://github.com/yue1123/vue3-baidu-map-gl/assets/54610382/44ba4cdd-6e40-4dad-8048-d9131b433fb5)

**Comment by yue1123** [comment]
是在 `@pluginReady` 事件中调用setPath的吗，请参考哈文档中的实现 [demo](https://yue1123.github.io/vue3-baidu-map-gl/zh-CN/hooks/useTrackAnimation)

**Comment by Rickmoti** [comment]
就是原封不动的引入demo报的错误，其它demo是正常的就是用了这个下面的demo就运行报错
![image](https://github.com/yue1123/vue3-baidu-map-gl/assets/54610382/f5af4714-eec2-4129-a845-332c0715f355)

**Comment by yue1123** [comment]
能否提供下最小化的项目，我复现一下

**Comment by Rickmoti** [comment]
> 能否提供下最小化的项目，我复现一下

感谢，我刚刚重新建一个vue3的项目引入是没报错的，但是我现在用的是ruoyi-vue3的官方项目的基础框架，在它上加Hooks中的demo页面就会报我上面提及的错误，

**Comment by Rickmoti** [comment]
> 能否提供下最小化的项目，我复现一下

vite升级4版本就行，vit3的版本不行

**Comment by iroboteer** [comment]
升级到vite4.3.9，还是报同样的错误；
