### ISSUE TITLE
打包部署之后服务器不加载地图

### ISSUE THREAD

**Issue by Rickmoti** [yue1123/vue3-baidu-map-gl#56]
打包部署之后服务器不加载地图
![image](https://github.com/yue1123/vue3-baidu-map-gl/assets/54610382/3a888b8b-843e-4981-8e2f-63c78f84695b)

**Comment by Rickmoti** [comment]
vite打包没打进去

**Comment by Rickmoti** [comment]
vite版本要4以上的才行，希望作者标注一下

**Comment by yue1123** [comment]
OK，感谢反馈，我会在文档中标注下。
