### ISSUE TITLE
按照示例使用useTrackAnimation时at init (useTrackAnimation.js:28:48)报错，Uncaught TypeError: Cannot read properties of undefined (reading 'getMapInstance')

### ISSUE THREAD

**Issue by iroboteer** [yue1123/vue3-baidu-map-gl#57]
**Describe the bug** A clear and concise description of what the bug is.
![Screen Shot 2023-11-23 at 10 30 34](https://github.com/yue1123/vue3-baidu-map-gl/assets/6365729/6b2efb50-3991-4680-865b-df7c8cc16844)

**Comment by yue1123** [comment]
same as https://github.com/yue1123/vue3-baidu-map-gl/issues/54
