### ISSUE TITLE
useParentComponentEffect.ts 这个hook看不太懂，作者可以解答下吗？help

### ISSUE THREAD

**Issue by E1FANG** [yue1123/vue3-baidu-map-gl#60]
useParentComponentEffect.ts
![image](https://github.com/yue1123/vue3-baidu-map-gl/assets/40976552/f132cd63-c260-4259-a907-f362d498a859)

components/overlay/polygon/index.vue
![image](https://github.com/yue1123/vue3-baidu-map-gl/assets/40976552/961caf21-3117-44c3-a5d3-f1784b14cdba)

主要是这个ready不知道是干嘛的

**Comment by yue1123** [comment]
这个 ready 主要有两个用途：
1. 触发组件本身的 initd 事件
2. 发布事件（组件可能有子组件，子组件依赖该父组件的实例，可以看下下面这张图代码里面的注释）

![image](https://github.com/yue1123/vue3-baidu-map-gl/assets/61490799/54e7c8b5-a930-40e6-8c16-43172ab02362)
