### ISSUE TITLE
首次打开在el-dialog中使用useTrackAnimation画路径可以，当再次打开el-dialog画路径就不显示

### ISSUE THREAD

**Issue by iroboteer** [yue1123/vue3-baidu-map-gl#61]
首次打开在el-dialog中使用useTrackAnimation画路径可以，当再次打开el-dialog使用useTrackAnimation画路径就不显示路径，需要刷新浏览器后才可以。

console显示如下错误：
![Screen Shot 2024-01-11 at 17 12 35](https://github.com/yue1123/vue3-baidu-map-gl/assets/6365729/c79ff9ef-92a9-4c71-a2fb-9d36f766f4a0)

![Screen Shot 2024-01-11 at 17 18 36](https://github.com/yue1123/vue3-baidu-map-gl/assets/6365729/96b7fa58-c08b-43e6-bdb6-caa54b8bad18)

**Comment by yue1123** [comment]
能够提供一下最小复现代码

**Comment by iroboteer** [comment]
> 能否提供一下最小复现代码

1、明天提供给你。

2、我发现如果去掉destroy-on-close就没有这个问题了。

3、但是带了新的问题，就是第一次打开的时候画的什么路径，后面再次打开el-dialog，不管后续setPath的时候设置的什么数据进去，都是重复画第一次设置的路径，除非我刷新浏览器。

**Comment by yue1123** [comment]
break, wait for reply
