### ISSUE TITLE
请问如何禁止地图, 手机移动端中禁止双指 操作 地图 旋转 或 倾斜?

### ISSUE THREAD

**Issue by kood-2008** [yue1123/vue3-baidu-map-gl#62]
操作: 我在手机移动中使用地图时,双指缩放操作发现有时候会旋转或者倾斜地图, 
期待: 但是我并不想要地图旋转, 倾斜,是否有api可以禁止!
尝试: 在百度文档中我看到这个代码和api代码

![Snipaste_2024-01-16_09-32-50](https://github.com/yue1123/vue3-baidu-map-gl/assets/80763000/c452664f-182c-4c1b-94c6-3eef644480fe)
`<b-map
        height="100vh"
        width="100vw"
        :enable-rotate="false"
        :enableTilt="false"
        :center="currentPosition"
        :zoom="10"
        @initd="handleInitd"
      >`  
或者
`const handleInitd = ({ map, BMapGL }) => {
        map.enableScrollWheelZoom(true)
        map.enableRotate(false)
        map.enableTilt(false)
        //map.enableTilt(false) `

![Snipaste_2024-01-16_09-35-08](https://github.com/yue1123/vue3-baidu-map-gl/assets/80763000/b0fc2cd6-7f01-4926-99ea-3880c661c959)

或者api文档提供
` <b-map
        height="100vh"
        width="100vw"
        :enable-rotate-gestures="false"
        :center="currentPosition"
        :zoom="10"
        @initd="handleInitd"
      >`
`   const handleInitd = ({ map, BMapGL }) => {
        map.enableScrollWheelZoom(true)
        map.enableRotateGestures(false)`

最终但是我尝试多种api 都无法阻止双指旋转地图

**Comment by yue1123** [comment]
试试 [enablePinchToZoom](https://yue1123.github.io/vue3-baidu-map-gl/zh-CN/components/map#%E5%8A%A8%E6%80%81%E7%BB%84%E4%BB%B6-props)
![image](https://github.com/yue1123/vue3-baidu-map-gl/assets/61490799/419a8239-82c0-410e-9974-dfeb370b5b25)

**Comment by kood-2008** [comment]
> 试试 [enablePinchToZoom](https://yue1123.github.io/vue3-baidu-map-gl/zh-CN/components/map#%E5%8A%A8%E6%80%81%E7%BB%84%E4%BB%B6-props) ![image](https://private-user-images.githubusercontent.com/61490799/296958652-419a8239-82c0-410e-9974-dfeb370b5b25.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzOTIxNjQsIm5iZiI6MTcwNTM5MTg2NCwicGF0aCI6Ii82MTQ5MDc5OS8yOTY5NTg2NTItNDE5YTgyMzktODJjMC00MTBlLTk5NzQtZGZlYjM3MGI1YjI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDA3NTc0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyYWE1Nzk5YjU1YTNjNWNmMGY3NDgwZmE1OWYyYjdjZmU0MTU4MGNkMTM1ODQ4MmYxYTExMDk3ODFiY2U2OTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jHhBp_cW20R_LyY0Fyk1Q7CuYQ384z0g099QlDuywG4)

手指缩放的功能还是要的,不然禁用只能移动地图, 跟老大沟通下旋转就算了,谢谢作者reply
