### ISSUE TITLE
BMarker 

### ISSUE THREAD

**Issue by a445073286** [yue1123/vue3-baidu-map-gl#64]
BMarker 只能用base64格式吗？支不支持gif类型图片，我引用本地路径的图片不管用什么方法都不显示，gif也不会动

**Comment by yue1123** [comment]
可以用其他的，只是 base64 不用处理路径问题。gif 貌似是不支持的，具体你看下百度地图官方文档

**Comment by a445073286** [comment]
> 可以用其他的，只是 base64 不用处理路径问题，本地不显示你注意看下图片路径。gif 貌似是不支持的，具体你参考百度地图官方文档
好的 感谢答复
