### ISSUE TITLE
texture  纹理 贴图怎么用？ 在线急等 ！！

### ISSUE THREAD

**Issue by LIANKONGYINGYING** [yue1123/vue3-baidu-map-gl#66]
我是@pluginReady方法加载 geojson 数据
![image](https://github.com/yue1123/vue3-baidu-map-gl/assets/30613166/12818800-b1a1-400c-bf26-3f24121be408)
 1、这个texture 注释数据加载成功，我想在这个乎数据加载成功的同时，在这个模型上再贴上这个纹理
这是成功后的 打开后的就不行了，这个怎么贴图呢，还是我弄方式不对，麻烦告知一下 谢谢
2、还有一个就是 mapvgl 这个以插件方式引入 怎么使用呢，控制台打印不到？
![image](https://github.com/yue1123/vue3-baidu-map-gl/assets/30613166/87353020-42d8-487c-82e7-cdabd55d8b4a)

**Comment by yue1123** [comment]
mapvgl 的纹理贴图这个我也不清楚，没办法帮你解答。第二个问题你是在 pluginReady 事件触发后再访问的 mapvgl 吗？

**Comment by yue1123** [comment]
https://yue1123.github.io/vue3-baidu-map-gl/zh-CN/expand/mapv#_1-%E9%80%9A%E8%BF%87%E7%BB%84%E4%BB%B6%E5%BA%93%E6%8F%90%E4%BE%9B%E7%9A%84%E6%8F%92%E4%BB%B6%E5%BD%A2%E5%BC%8F-%E5%86%85%E9%83%A8%E4%BB%A5-cdn-%E6%96%B9%E5%BC%8F%E5%8A%A0%E8%BD%BD 看下这个页面的代码和 demo 吧

**Comment by LIANKONGYINGYING** [comment]
我就这么写的&nbsp; ，代码在这 ，能给看看吗？
至于你说的这个 pluginReady 事件触发后再访问的 mapvgl 问题，我还真不知道怎么用，代码发给你了 帮我看一下呗，谢谢了


????????&nbsp;?????
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yue1123/vue3-baidu-map-gl"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月25日(星期四) 中午11:16
***@***.***&gt;;
抄送:&nbsp;"ۋاقىتنىڭ ***@***.******@***.***&gt;;
主题:&nbsp;Re: [yue1123/vue3-baidu-map-gl] texture  纹理 贴图怎么用？ 在线急等 ！！ (Issue #66)





 
https://yue1123.github.io/vue3-baidu-map-gl/zh-CN/expand/mapv#_1-%E9%80%9A%E8%BF%87%E7%BB%84%E4%BB%B6%E5%BA%93%E6%8F%90%E4%BE%9B%E7%9A%84%E6%8F%92%E4%BB%B6%E5%BD%A2%E5%BC%8F-%E5%86%85%E9%83%A8%E4%BB%A5-cdn-%E6%96%B9%E5%BC%8F%E5%8A%A0%E8%BD%BD 看下这个页面的代码和 demo 吧

**Comment by yue1123** [comment]
代码看不到。文档有写怎么用，也有 demo 代码，上面的链接就是。

**Comment by LIANKONGYINGYING** [comment]
![image](https://github.com/yue1123/vue3-baidu-map-gl/assets/30613166/50233857-f1f4-4000-8b23-50028302178e)
![image](https://github.com/yue1123/vue3-baidu-map-gl/assets/30613166/03c4e37f-447b-4735-a4a6-3bf06c349534)
![image](https://github.com/yue1123/vue3-baidu-map-gl/assets/30613166/a39e7a8f-d766-46a0-b0ac-3419e6584478)
![image](https://github.com/yue1123/vue3-baidu-map-gl/assets/30613166/316928c6-29ed-42c6-ace0-97b7335749bf)
![image](https://github.com/yue1123/vue3-baidu-map-gl/assets/30613166/82b529ec-3757-489d-9215-c34220ffc693)

就这点代码 没多少，主要是在最后这个图上，最后就是你说的这个（你是在 pluginReady 事件触发后再访问的 mapvgl) 我还真不知道怎么用？这mpvgl  从哪能接收到？

**Comment by yue1123** [comment]
pluginReady 触发后，mapvgl 全局 window 就有，你这里报错应该是 ts 定义问题

**Comment by LIANKONGYINGYING** [comment]
组件 这个mapvgl 不能用吗？

**Comment by yue1123** [comment]
这个组件库没有对 mapvgl做任何的组件封装，只是做了插件加载

**Comment by LIANKONGYINGYING** [comment]
![image](https://github.com/yue1123/vue3-baidu-map-gl/assets/30613166/a1733125-5aff-4b71-9f13-7207329c8032)
那要是这个示例上在这个上面贴图怎么弄呢

**Comment by LIANKONGYINGYING** [comment]
你们这个支持吗

**Comment by yue1123** [comment]
贴图看 mapvgl 文档吧，这个库只有地面叠加层支持
