### ISSUE TITLE
请问有离线版本吗？

### ISSUE THREAD

**Issue by Sandy-ABS** [yue1123/vue3-baidu-map-gl#67]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yue1123** [comment]
可以自己改地图sdk地址，文档配置页有写，你找找

**Comment by Sandy-ABS** [comment]
您好！
找到了文档配置页的说明。其中apiUrl属性设置自建地图 api 资源地址（一般用于离线地图）。
请问这个离线地图是否提供一个下载方式，并提供一下调用离线地图的程序例子。
谢谢！



Sandy

***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yue1123/vue3-baidu-map-gl"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月13日(星期一) 下午5:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yue1123/vue3-baidu-map-gl] 请问有离线版本吗？ (Issue #67)





 
可以自己改地图sdk地址，文档配置页有写，你找找

**Comment by yue1123** [comment]
没有，百度谷歌搜一个api sdk下载下来，配置本地自建API url就好了
