### ISSUE TITLE
BMarker标注点组件中的title如果长度过长，将显示超出lable的框，应该有自动换行的处理。

### ISSUE THREAD

**Issue by Sandy-ABS** [yue1123/vue3-baidu-map-gl#68]
**Describe the bug** A clear and concise description of what the bug is.

**To Reproduce** Steps to reproduce the behavior:

**Expected behavior** A clear and concise description of what you expected to happen.

**Screenshots** If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context** Add any other context about the problem here.

**Comment by Sandy-ABS** [comment]
写错了，是[BInfoWindow 信息窗口]有这种不能自动换行的问题

**Comment by yue1123** [comment]
这个应该是百度sdk本身的问题，不属于这个组件库issue范畴

**Comment by Sandy-ABS** [comment]
你好！谢谢回复。


百度地图中的infowindows组件，titile长度是不换行的，但是还有个message描述信息，是可以换行的，目前这个组件中没有message.


建议infowindows组件中增加message这个属性。





张定京
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yue1123/vue3-baidu-map-gl"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月13日(星期一) 下午5:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yue1123/vue3-baidu-map-gl] BMarker标注点组件中的title如果长度过长，将显示超出lable的框，应该有自动换行的处理。 (Issue #68)





 
这个应该是百度sdk本身的问题，不属于这个组件库issue范畴

**Comment by yue1123** [comment]
好的，感谢反馈。如果你有兴趣，也可以尝试PR加一下这个属性👏

**Comment by Sandy-ABS** [comment]
你好！请问怎么PR加属性？
我是通过git下载了源码，想加一下属性，但是源码还没改，编译就报了20给错。


张定京
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yue1123/vue3-baidu-map-gl"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月13日(星期一) 下午5:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yue1123/vue3-baidu-map-gl] BMarker标注点组件中的title如果长度过长，将显示超出lable的框，应该有自动换行的处理。 (Issue #68)





 
好的，感谢反馈。如果你有兴趣，也可以尝试PR加一下这个属性👏

**Comment by yue1123** [comment]
你开发环境可能不对，没关系，我来处理吧

**Comment by Sandy-ABS** [comment]
又调试了一下，还是编译不过去，编译环境不兼容。
您那边解决后，烦请通知我。
非常感谢！



Sandy

***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yue1123/vue3-baidu-map-gl"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月13日(星期一) 晚上10:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yue1123/vue3-baidu-map-gl] BMarker标注点组件中的title如果长度过长，将显示超出lable的框，应该有自动换行的处理。 (Issue #68)





 
你开发环境可能不对，没关系，我来处理吧
