### ISSUE TITLE
地图的高度如何设置为容器的高度

### ISSUE THREAD

**Issue by redwolf1996** [yue1123/vue3-baidu-map-gl#70]
请问组件的height应该如何设置，才能自适应父容器的高度，设置100%无效
![image](https://github.com/yue1123/vue3-baidu-map-gl/assets/9690393/8c2341e7-fb2e-46e5-8537-557cd77868c8)

**Comment by sisabyss** [comment]
同求，有解决方案了吗

**Comment by yue1123** [comment]
再写一个style="height:100%"试试

**Comment by sisabyss** [comment]
> 再写一个style="height:100%"试试

疑似不支持百分比，我是这样解决的：
```js
const screenHeight = ref(window.innerHeight);

const updateHeight = () => {
  screenHeight.value = window.innerHeight;
};
```
```html
<BMap :height="screenHeight"/>
```

**Comment by yue1123** [comment]
不支持百分比是因为渲染容器外层还有一个div（也就是map组件根节点），这个div高度没有继承，所以再加一个`style="height:100%"`就可以生效了，这个下个小版本会优化下

**Comment by redwolf1996** [comment]
> 同求，有解决方案了吗

刚看到，发现作者已经解决了 ：）

**Comment by redwolf1996** [comment]
> 不支持百分比是因为渲染容器外层还有一个div（也就是map组件根节点），这个div高度没有继承，所以再加一个`style="height:100%"`就可以生效了，这个下个小版本会优化下

谢谢
