### ISSUE TITLE
displayOptions配置项 skyColors 说明错误

### ISSUE THREAD

**Issue by myltx** [yue1123/vue3-baidu-map-gl#74]
## 当前文档`skyColors`说明：
![image](https://github.com/user-attachments/assets/0bd76b1c-bca2-41e4-88d2-408b3074fa61)
## 百度官方 `skyColors` 说明:
![image](https://github.com/user-attachments/assets/8f61f9c2-a9d4-45bc-ad3d-f03117e2dc53)

**Comment by yue1123** [comment]
close as #75
