### ISSUE TITLE
BMarker使用@rightClick时方法貌似没有起作用

### ISSUE THREAD

**Issue by 3246046194** [yue1123/vue3-baidu-map-gl#78]
在打印ref时onRightClick没有被赋值该函数 显示是undefined，希望作者查看!

**Comment by yue1123** [comment]
已经修复了，升级2.3.5 试试

**Comment by 3246046194** [comment]
> 已经修复了，升级2.3.5 试试 已经修复了，升级2.3.5 试试

2.3.5的BMarker好像出现了问题升级后显示不出来了
![Uploading 微信图片_20240807144207.png…]()

**Comment by 3246046194** [comment]
TypeError: Cannot read properties of null(reading 'insertBefore”)

**Comment by yue1123** [comment]
我这边测试是能正常渲染的，你再确认下是否是升级成功，依赖是否有缓存之类的。如果你的marker点是异步填充的，需要用visible来控制显示。
[playground](https://play.vuejs.org/#eNqtV1lz2kgX/SsqvvoqD4mFVhZPZioEMY4ybmGMSALlFyEpQguIkgRaUvnvc24LDM6sD1NlsLr7rueee2l964z2e/F48Du3nbeFv90nTuH/8rQThLfvmbMXytArNj8/dWRJ+v9TR9j4YbAp2vVxgw0nxiJWj3f2bL5m5W/e5kv462932d08bpLYnu8Hd4c95Pyds078uZulSfJ54/vJKk235EYQbl1/V/gZ7HwT4P1WUIfiUNblgf5GSHbBrSDLPVGT1KEkC9+fOjy4Nrws9jPhdp/mYRGmu38yIJ0MCLeh20q3lgQh3DqBv8iSW+GV5xTOLV9382PwutomP62d3O9pbx6Mobb+XAbe9lPtKslxHUkhm2ulGb5P1lvruLpLDqtGCj99ery7t4PwodEGrrramR+8/erDY/owN6Xp2Aycu0/7lbKRzmtvmySe9PHoG7A3HpWmMdP4J3y/dT5X+cP842Gt6AnW8F8dXPhwPjxKrpEe71VP9WpdZbV+dLfukUWjko2Hjbd1w4eoKpdfHlPzbrVf35WFu/uUr2wpXH1ZId5hvILvpVLt3bFce5+rBH4S5AZfjzF8xVhbLJoF1oRVLNR0y541iCuwxqMXaxY9GthrLGBhGQvVNCb1fRTLlsECi59Dx3g0WLM4MGMmW/VIgjx9rnRmkmmY0qyh/xf9ax06N41Hx7ZH3CewqthYU6FfQ6e8j1zJss0A+zVsl7OGqfeRCTsB7QHra3nCmPvD/yu5xj2waEGy9CE70pTyf6EH/xc51MuUPodmsNom+Ro1NBvUwKA6mMf/pAZ2fGB20DDCba5JVjNRZs1EA0ba1A6ALTCKzGo6H1XTsaZPjZj4QxjqVgMML/oNztWpvTGYjfjtSUU1wJ5mRbECDOX7KCipXqwJDlZjyoQZfNaWvUStGXwyxYo86M8OqA/qRtgFNce21hRmL3XsKffRBHIufJuHqRHobI5aU2z2QkfsiG0CWfLDcG7KOCeMUQPup7mPlqh1jLNYYsaCywFzjUlMR60k5INakBxyiBbBlHjUBCUwaMBNcIrnU8GOzmziEcWxUKwFQ85aA07BPvejsAZxtPkQhsRJ4DEiHgMP8CIi/SX5l7g+7E+NEexTnoE2JZ7aAXi6AFbQDzXkzmToU42kllfQjxbVFPqIVQO+FD/hjfzaGlmNS3wjnBCfixpOkGvcoFY8fwu8siRWA6cK6+qUP+RRd/CCRciS740Q38mmMVLRO6i9Bk4yteXNorHsE6YG/NW8duhnRrVDbeCH88Y8gBcycqqtGrVpRsQ7YDojnRo6iIOwIzsLDTWk2GrsIbYJ4ohrFsUcG/BUPWEvTe34hM0E2J6xn2nwQ9g2qBP1M/RdBbLcPrjUIHc6h32OLc6ZDH602NtMojxgn2ICDoTdTG3jA/bUjy326J8Z1Ra1Q95Um2hC/dP6B0ct24V/UyIc2trMEP9CZTGr4V9FX1z2Qo6NCjzJJ9WzwlyETfSPPZFwzvkC/xWiIu4ipkkbkx3wGUN84P0D2y12DL7B1QixXXKnGiLf4ORnoaM2nNdWs9ROvc/9tBxgOp+fF+yJVyU4ceYV5hnpL4E9eE21o3rahA35j+F/iTxc5OGWVsz9w+eE+gazdoEepL6YkH2ZZgviB69MxEd5Yq7Q7D9zDLyl2YNn1K7tW0Yc5DihrtS3tVaj9jg3OUf5OfHeRg8uuL4Mfyf9QMNM4vrwr1HfUHyYXeAw+V9KNBfo9wMxVxw/5A/71COoPTCNUMdmRHOQciZMzvUANhP094z6XzrHPrWp52lvhrmLGsI3eF/SbwVmhoJ649zEPFyA9xM+l9FHXB8cQO0IW9IPNM6bOXoK86ndA94G5YNesJcK6kk2MS+XMniDfIkPMWwSl8FVxEl4oZ4UE3G55nMGXEbvn/2gXr8auBMAI/RaG6fG7BHVCDUEZtDhcUbgUDtHKujT7zrlqTJ75VzuIWbE+wgfMxy8fmjvGa9fvTlfo/Kw8W+F51uV0F4ecf2SpGcZ4XSF5Lvnze/tA93N3mV06iahSxdL3NPyNPHFJA2e75BG5gRBuAuEbntN7dI9FY9vu1fXVyxzNwv3BS6EuwCWihwGcr84kGi43adZIXwTSPUNffOb5Hfha5ZuhVe4Das3ayf0DjdbZ38TJK/Iemvvl86bTqtOZ2KUpzvcnHnOT6cDeHpG4akDY7R+6myKYp/fdruut4Oa5yfhMRN3ftHd7bfddxDrZoddEW79Gy/dvlNFVdS6XpgX19uin29v1lla5n4GI0+dE67cTRebRz+7yfyd52d+9m/d/qB27fqHo79279U7Zxu6Od/90W0e13vHjUXPP3ZfCF5H/xLxfxH7H3TeKQhcbwMPEXBF4XI/5AYc+47a3aeuQy8LJqj1J689T8VbXPsvbz29F+88tDqGfvk+rbCUBEnQBvjD7tcwSbC1S3eotoC3hl2OJcWP8MuyFEtVTLOgq0iSRC8WeI15u3eKjeBBjA3Fgd4f9ARVEft6Xxv3REUd6ANBVcWBpiqCJqi6qJ6e+mNN0CRRldW+ICviUNdUAX8KdtUx5CRN79OGdhHDI6ldmZHFfk/G+uRAHYiypsjnAKhViiyNfQT3v16P0m7XN2dgLiI3SbjzXWePzfWhKF7uR2lIL1pZeth5T53udc6IV9XH/BvBCUpP1CUKU8C7Wm8gD8Z4HIq9fn+AXVmU+0PkwbMcQ2KgSMgQL3bPMng8a+LxZK41z79Xf6jSJcXhcPiPKf59KooyhkuOqaIIylCQh6cVHvtj+taoqD2KjB/IEKPvsSK3B9iQL2L02B/T99nQSYzMk5P/PB+i5Y9j9DKM0TpFjp75GgY/DD033e7DxM+me+qrl8PPSZK0/Mj3iuzgP/e7u/Hd+E/2o7xqO/8h8/nsuZoRhZMFPvhFx5O55Vd4fj7cpt4hOQ3avzh89PFTcqAYW7H3SBxhX8nxaE0+w/H7YueTqvB3+TkpCpQPEi7PZ9b4b1K/hIt5+jyAvv8OgcSAvg==)

**Comment by 3246046194** [comment]
> 我这边测试是能正常渲染的，你再确认下是否是升级成功，依赖是否有缓存之类的。如果你的marker点是异步填充的，需要用visible来控制显示。 [playground](https://play.vuejs.org/#eNqtV1lz2kgX/SsqvvoqD4mFVhZPZioEMY4ybmGMSALlFyEpQguIkgRaUvnvc24LDM6sD1NlsLr7rueee2l964z2e/F48Du3nbeFv90nTuH/8rQThLfvmbMXytArNj8/dWRJ+v9TR9j4YbAp2vVxgw0nxiJWj3f2bL5m5W/e5kv462932d08bpLYnu8Hd4c95Pyds078uZulSfJ54/vJKk235EYQbl1/V/gZ7HwT4P1WUIfiUNblgf5GSHbBrSDLPVGT1KEkC9+fOjy4Nrws9jPhdp/mYRGmu38yIJ0MCLeh20q3lgQh3DqBv8iSW+GV5xTOLV9382PwutomP62d3O9pbx6Mobb+XAbe9lPtKslxHUkhm2ulGb5P1lvruLpLDqtGCj99ery7t4PwodEGrrramR+8/erDY/owN6Xp2Aycu0/7lbKRzmtvmySe9PHoG7A3HpWmMdP4J3y/dT5X+cP842Gt6AnW8F8dXPhwPjxKrpEe71VP9WpdZbV+dLfukUWjko2Hjbd1w4eoKpdfHlPzbrVf35WFu/uUr2wpXH1ZId5hvILvpVLt3bFce5+rBH4S5AZfjzF8xVhbLJoF1oRVLNR0y541iCuwxqMXaxY9GthrLGBhGQvVNCb1fRTLlsECi59Dx3g0WLM4MGMmW/VIgjx9rnRmkmmY0qyh/xf9ax06N41Hx7ZH3CewqthYU6FfQ6e8j1zJss0A+zVsl7OGqfeRCTsB7QHra3nCmPvD/yu5xj2waEGy9CE70pTyf6EH/xc51MuUPodmsNom+Ro1NBvUwKA6mMf/pAZ2fGB20DDCba5JVjNRZs1EA0ba1A6ALTCKzGo6H1XTsaZPjZj4QxjqVgMML/oNztWpvTGYjfjtSUU1wJ5mRbECDOX7KCipXqwJDlZjyoQZfNaWvUStGXwyxYo86M8OqA/qRtgFNce21hRmL3XsKffRBHIufJuHqRHobI5aU2z2QkfsiG0CWfLDcG7KOCeMUQPup7mPlqh1jLNYYsaCywFzjUlMR60k5INakBxyiBbBlHjUBCUwaMBNcIrnU8GOzmziEcWxUKwFQ85aA07BPvejsAZxtPkQhsRJ4DEiHgMP8CIi/SX5l7g+7E+NEexTnoE2JZ7aAXi6AFbQDzXkzmToU42kllfQjxbVFPqIVQO+FD/hjfzaGlmNS3wjnBCfixpOkGvcoFY8fwu8siRWA6cK6+qUP+RRd/CCRciS740Q38mmMVLRO6i9Bk4yteXNorHsE6YG/NW8duhnRrVDbeCH88Y8gBcycqqtGrVpRsQ7YDojnRo6iIOwIzsLDTWk2GrsIbYJ4ohrFsUcG/BUPWEvTe34hM0E2J6xn2nwQ9g2qBP1M/RdBbLcPrjUIHc6h32OLc6ZDH602NtMojxgn2ICDoTdTG3jA/bUjy326J8Z1Ra1Q95Um2hC/dP6B0ct24V/UyIc2trMEP9CZTGr4V9FX1z2Qo6NCjzJJ9WzwlyETfSPPZFwzvkC/xWiIu4ipkkbkx3wGUN84P0D2y12DL7B1QixXXKnGiLf4ORnoaM2nNdWs9ROvc/9tBxgOp+fF+yJVyU4ceYV5hnpL4E9eE21o3rahA35j+F/iTxc5OGWVsz9w+eE+gazdoEepL6YkH2ZZgviB69MxEd5Yq7Q7D9zDLyl2YNn1K7tW0Yc5DihrtS3tVaj9jg3OUf5OfHeRg8uuL4Mfyf9QMNM4vrwr1HfUHyYXeAw+V9KNBfo9wMxVxw/5A/71COoPTCNUMdmRHOQciZMzvUANhP094z6XzrHPrWp52lvhrmLGsI3eF/SbwVmhoJ649zEPFyA9xM+l9FHXB8cQO0IW9IPNM6bOXoK86ndA94G5YNesJcK6kk2MS+XMniDfIkPMWwSl8FVxEl4oZ4UE3G55nMGXEbvn/2gXr8auBMAI/RaG6fG7BHVCDUEZtDhcUbgUDtHKujT7zrlqTJ75VzuIWbE+wgfMxy8fmjvGa9fvTlfo/Kw8W+F51uV0F4ecf2SpGcZ4XSF5Lvnze/tA93N3mV06iahSxdL3NPyNPHFJA2e75BG5gRBuAuEbntN7dI9FY9vu1fXVyxzNwv3BS6EuwCWihwGcr84kGi43adZIXwTSPUNffOb5Hfha5ZuhVe4Das3ayf0DjdbZ38TJK/Iemvvl86bTqtOZ2KUpzvcnHnOT6cDeHpG4akDY7R+6myKYp/fdruut4Oa5yfhMRN3ftHd7bfddxDrZoddEW79Gy/dvlNFVdS6XpgX19uin29v1lla5n4GI0+dE67cTRebRz+7yfyd52d+9m/d/qB27fqHo79279U7Zxu6Od/90W0e13vHjUXPP3ZfCF5H/xLxfxH7H3TeKQhcbwMPEXBF4XI/5AYc+47a3aeuQy8LJqj1J689T8VbXPsvbz29F+88tDqGfvk+rbCUBEnQBvjD7tcwSbC1S3eotoC3hl2OJcWP8MuyFEtVTLOgq0iSRC8WeI15u3eKjeBBjA3Fgd4f9ARVEft6Xxv3REUd6ANBVcWBpiqCJqi6qJ6e+mNN0CRRldW+ICviUNdUAX8KdtUx5CRN79OGdhHDI6ldmZHFfk/G+uRAHYiypsjnAKhViiyNfQT3v16P0m7XN2dgLiI3SbjzXWePzfWhKF7uR2lIL1pZeth5T53udc6IV9XH/BvBCUpP1CUKU8C7Wm8gD8Z4HIq9fn+AXVmU+0PkwbMcQ2KgSMgQL3bPMng8a+LxZK41z79Xf6jSJcXhcPiPKf59KooyhkuOqaIIylCQh6cVHvtj+taoqD2KjB/IEKPvsSK3B9iQL2L02B/T99nQSYzMk5P/PB+i5Y9j9DKM0TpFjp75GgY/DD033e7DxM+me+qrl8PPSZK0/Mj3iuzgP/e7u/Hd+E/2o7xqO/8h8/nsuZoRhZMFPvhFx5O55Vd4fj7cpt4hOQ3avzh89PFTcqAYW7H3S

> 我这边测试是能正常渲染的，你再确认下是否是升级成功，依赖是否有缓存之类的。如果你的marker点是异步填充的，需要用visible来控制显示。 [playground](https://play.vuejs.org/#eNqtV1lz2kgX/SsqvvoqD4mFVhZPZioEMY4ybmGMSALlFyEpQguIkgRaUvnvc24LDM6sD1NlsLr7rueee2l964z2e/F48Du3nbeFv90nTuH/8rQThLfvmbMXytArNj8/dWRJ+v9TR9j4YbAp2vVxgw0nxiJWj3f2bL5m5W/e5kv462932d08bpLYnu8Hd4c95Pyds078uZulSfJ54/vJKk235EYQbl1/V/gZ7HwT4P1WUIfiUNblgf5GSHbBrSDLPVGT1KEkC9+fOjy4Nrws9jPhdp/mYRGmu38yIJ0MCLeh20q3lgQh3DqBv8iSW+GV5xTOLV9382PwutomP62d3O9pbx6Mobb+XAbe9lPtKslxHUkhm2ulGb5P1lvruLpLDqtGCj99ery7t4PwodEGrrramR+8/erDY/owN6Xp2Aycu0/7lbKRzmtvmySe9PHoG7A3HpWmMdP4J3y/dT5X+cP842Gt6AnW8F8dXPhwPjxKrpEe71VP9WpdZbV+dLfukUWjko2Hjbd1w4eoKpdfHlPzbrVf35WFu/uUr2wpXH1ZId5hvILvpVLt3bFce5+rBH4S5AZfjzF8xVhbLJoF1oRVLNR0y541iCuwxqMXaxY9GthrLGBhGQvVNCb1fRTLlsECi59Dx3g0WLM4MGMmW/VIgjx9rnRmkmmY0qyh/xf9ax06N41Hx7ZH3CewqthYU6FfQ6e8j1zJss0A+zVsl7OGqfeRCTsB7QHra3nCmPvD/yu5xj2waEGy9CE70pTyf6EH/xc51MuUPodmsNom+Ro1NBvUwKA6mMf/pAZ2fGB20DDCba5JVjNRZs1EA0ba1A6ALTCKzGo6H1XTsaZPjZj4QxjqVgMML/oNztWpvTGYjfjtSUU1wJ5mRbECDOX7KCipXqwJDlZjyoQZfNaWvUStGXwyxYo86M8OqA/qRtgFNce21hRmL3XsKffRBHIufJuHqRHobI5aU2z2QkfsiG0CWfLDcG7KOCeMUQPup7mPlqh1jLNYYsaCywFzjUlMR60k5INakBxyiBbBlHjUBCUwaMBNcIrnU8GOzmziEcWxUKwFQ85aA07BPvejsAZxtPkQhsRJ4DEiHgMP8CIi/SX5l7g+7E+NEexTnoE2JZ7aAXi6AFbQDzXkzmToU42kllfQjxbVFPqIVQO+FD/hjfzaGlmNS3wjnBCfixpOkGvcoFY8fwu8siRWA6cK6+qUP+RRd/CCRciS740Q38mmMVLRO6i9Bk4yteXNorHsE6YG/NW8duhnRrVDbeCH88Y8gBcycqqtGrVpRsQ7YDojnRo6iIOwIzsLDTWk2GrsIbYJ4ohrFsUcG/BUPWEvTe34hM0E2J6xn2nwQ9g2qBP1M/RdBbLcPrjUIHc6h32OLc6ZDH602NtMojxgn2ICDoTdTG3jA/bUjy326J8Z1Ra1Q95Um2hC/dP6B0ct24V/UyIc2trMEP9CZTGr4V9FX1z2Qo6NCjzJJ9WzwlyETfSPPZFwzvkC/xWiIu4ipkkbkx3wGUN84P0D2y12DL7B1QixXXKnGiLf4ORnoaM2nNdWs9ROvc/9tBxgOp+fF+yJVyU4ceYV5hnpL4E9eE21o3rahA35j+F/iTxc5OGWVsz9w+eE+gazdoEepL6YkH2ZZgviB69MxEd5Yq7Q7D9zDLyl2YNn1K7tW0Yc5DihrtS3tVaj9jg3OUf5OfHeRg8uuL4Mfyf9QMNM4vrwr1HfUHyYXeAw+V9KNBfo9wMxVxw/5A/71COoPTCNUMdmRHOQciZMzvUANhP094z6XzrHPrWp52lvhrmLGsI3eF/SbwVmhoJ649zEPFyA9xM+l9FHXB8cQO0IW9IPNM6bOXoK86ndA94G5YNesJcK6kk2MS+XMniDfIkPMWwSl8FVxEl4oZ4UE3G55nMGXEbvn/2gXr8auBMAI/RaG6fG7BHVCDUEZtDhcUbgUDtHKujT7zrlqTJ75VzuIWbE+wgfMxy8fmjvGa9fvTlfo/Kw8W+F51uV0F4ecf2SpGcZ4XSF5Lvnze/tA93N3mV06iahSxdL3NPyNPHFJA2e75BG5gRBuAuEbntN7dI9FY9vu1fXVyxzNwv3BS6EuwCWihwGcr84kGi43adZIXwTSPUNffOb5Hfha5ZuhVe4Das3ayf0DjdbZ38TJK/Iemvvl86bTqtOZ2KUpzvcnHnOT6cDeHpG4akDY7R+6myKYp/fdruut4Oa5yfhMRN3ftHd7bfddxDrZoddEW79Gy/dvlNFVdS6XpgX19uin29v1lla5n4GI0+dE67cTRebRz+7yfyd52d+9m/d/qB27fqHo79279U7Zxu6Od/90W0e13vHjUXPP3ZfCF5H/xLxfxH7H3TeKQhcbwMPEXBF4XI/5AYc+47a3aeuQy8LJqj1J689T8VbXPsvbz29F+88tDqGfvk+rbCUBEnQBvjD7tcwSbC1S3eotoC3hl2OJcWP8MuyFEtVTLOgq0iSRC8WeI15u3eKjeBBjA3Fgd4f9ARVEft6Xxv3REUd6ANBVcWBpiqCJqi6qJ6e+mNN0CRRldW+ICviUNdUAX8KdtUx5CRN79OGdhHDI6ldmZHFfk/G+uRAHYiypsjnAKhViiyNfQT3v16P0m7XN2dgLiI3SbjzXWePzfWhKF7uR2lIL1pZeth5T53udc6IV9XH/BvBCUpP1CUKU8C7Wm8gD8Z4HIq9fn+AXVmU+0PkwbMcQ2KgSMgQL3bPMng8a+LxZK41z79Xf6jSJcXhcPiPKf59KooyhkuOqaIIylCQh6cVHvtj+taoqD2KjB/IEKPvsSK3B9iQL2L02B/T99nQSYzMk5P/PB+i5Y9j9DKM0TpFjp75GgY/DD033e7DxM+me+qrl8PPSZK0/Mj3iuzgP/e7u/Hd+E/2o7xqO/8h8/nsuZoRhZMFPvhFx5O55Vd4fj7cpt4hOQ3avzh89PFTcqAYW7H3SBxhX8nxaE0+w/H7YueTqvB3+TkpCpQPEi7PZ9b4b1K/hIt5+jyAvv8OgcSAvg==)

我回复您邮箱可以收到吗

**Comment by 3246046194** [comment]
我在训练场测试也有这个问题哦[测试](https://play.vuejs.org/#eNqtWFuP28YV/iuTDQI7iEXxpl1JcQJrJWXNZEmtVpSdXSxgUCSXS4kiBZK6kI6BAn0O2r4laYCiL0WBokEei7ZJ/0ycoP+i3xnqQq03jgvEXknDmXM/3zmcmecHrdlMWMzdg+bBw9SdzgIrdT+8Chl76PgLPsDwrUqF/fCv//z05fcv//mXl19/+/KP37/85oufvvsDq1Q2NMe6NWNL30lvPrg6kETxnasDduP63k1aPC9uMGFN8DBRFidmfzDSl584N5/6H31yEp8MJnkwMQez+sl8Bjo3tEaBO7DjKAie3rhucBlFUxa712CfWqAolDLWtN0wdWNMB5FtpX4UCrPID1P22WdsHjrutR+6DgQ+8kM/dUDmuSkemxBiZjO3EEejq4O1I+QK19aMrq8Tl6x/zlZNJssPWNZkqsheQEC1RK1b8cSNtxbNosQnQzgjwtlkSkNoSDWpXnvAgtBrMkk6FFRRbIgSydoy+nbBtJlgzJ9anjuMgya751ip1eTP1WThvbeaBu+PrMQ9VB+cdRrq6OnSc6ZPMlsOFqOx6OsDdan5x8FoaiwuT4L5ZS76T56cn5yann+Wq3VbuQy1x87s8vF5dDbQxF5b86yTJ7NL+UbcPDvTIHDEjxduB/LaraXW6av84x9Praer5Gzw8Xwk1wI8Q/9qbkOH9fhctDvR4lRxFCerKXpWW9hTe6GPW0u93cidqe2fjVfLi0/PI+3kcjY6WaZ2+CS5NEX/8tNL2NuYXEL3hbya2W0pc56uAugJ4Bt0nU+ga4JnQx/3PaOrr3RfrRlmP4ddntFu7T3r4/MO5nIDsTA6Q0XrdLPT8UQyOrpn8HXwdM47ej6c652+ZGQtEfT0KfH0Ra2jif2cfnf8ZR5a1zrnlmm2uE7EaqW3VQX8GXiWp2NbNEzNw3wG2ct+riunYw1yPJpDrMv0FGOuD78lutye6+Mh0dKH5Ig98n+PD/p3dMiXJj71Ne9yGiQj5FDLkYMO5UFb/Co5MCdz3fRyneI2UEUj78r9vKsiRmrP9BBbxGisrXqD1qrXVmu9zoTwQzGsGTliuOPPsa70zJuObsJ+s7uiHGBONcYTGTGUTsfekvKl597cyDWJYgadmWFeINc6dOqyMXbA358jP8gbxc7LeGwzVdbNixrm5NNxF3Q2dGvzXser6QPkmmwzhzXYDtu6oCU9OtY1CesUY+SA68lPxxfI9QRrE1HvDDkdYq7qol5DrkT4g1wQHXwYD70e4Sj3lohBDmwCU9yfFeTUdJNwRHYMZWOow2c1B6Ygn+uR9Rx2FP5QDAmTiEeLcIx4ABdj4r8g/SLnh/xepwX55Ken9ginpgecDhEr8PsqfNcl8FOOxAJX4B8PVz3ww1YV8SX7Kd7wr8iRkduEN4oT7LORwy58neTIFfffAK4MUc8QpxWeV2v/QY+8Axf6GF7yuRbsW8vstBTUDnKvApO6UuBmmBvmOqYd6Mt47lDPOuUOuYEejhttDlxI8CkzMuQmbxHuENM+8WTggR0UO5IzVJFDsi3DHGzrwo5Jpo8nPDbAqbKOvdgzJ+vYdBHbTez7KvRQbHPkieoZ/LYMWi4fWMrhO61DPo8t1nUJ+Chib+oi+QH5ZBPiQLHrK4V9iD3VYxF71E+fcovcwW/KzbhL9VPoB0YN04Z+TaQ4FLnpw/6hok/0DPoV1MVuzuexURBP0kn5XKEvQibqx+yKWOd4gf4VrCLswqZuYZPp8R5DeOD1A9lF7HToBlbHsG3nO+UQ/nprPcMacsNxbeQX6rr2uZ4CA3qN989d7AlXS2Bigyv0M+K/QOyBa8od5dOk2JD+CfRfwA8bfthLY8L1Q2eX6ga9dogapLroknyJegvsB6402Ed+oq9Q799gDLil3oMxclfUrU4Y5HFCXqluMzVD7rGucYzydcK9iRoccn4J+tb8noqexPmhX6W6IfvQu4Bh0n8hUl+g9wdsXvH4wX/IpxpB7hHTMfKYt6gPks8Uk00+EJsu6rtP9S9ubO+ZVPM010ffRQ6hG7hf0rsCPUNGvrGuoR8Ogfsu78uoI84PDCB3FFvi91SOmwFqCv2pmEO8O+QPasG8kJFPkol+eSEBN/CX8DCBTMIysAo7KV7IJ9lEWM54nwGWUfsbPcjXRx3sCRAj1Fphp6qbLcoRcoiYgYfbOQaGij6yAj+918lPRTcvrd0+RBvzOsJH8+vvnRX7jPfuPdhtpBI/d5ustLNixVYVezFRLNGx9ZaVz++mX2yGpe1aeQfY9tPs1E/SV/aMIt8zyq/uGQe2FbjMCu2biDavx3rr7FnLaD/unT877plmT392rp08Nm9xGdbC9/guV3HeiPmWPVJhj3THJrYdhSl223dLNXtnPydy30U7sJIES/Y8SaNpBRtaElraW0NV4gaunW5Ji0fwhtaU9uMY+bRRx++iMo0cN7hzk85FRTOKBVtYwZxYuclG71xvnT7DENQ/fvnNf3/zVXFieVgtyH9ZxKBldk9PNbO7lvLy87/9+MWf/l8p3da5+Xgj4etvf/r9b3/8659f/vt3d0h4WC2isMtHdZOQV1O0Y3sDBOyI7z7OSKJSgPoqLf4/sgPfplMaPyjt2O/OLNucuiqjNNyR76V7ZoVb7i156q4o54uKT0c6PzmNLMcPPQrVN1/98N3nP/zj74KAsIC5LOx0za9BP5jdIHFLIL4jaJsj7UbTW2VVJcHrQ9ze6W3/RAl6KCjI9jjbfmwHbhkOCWyYuIM0CwgMSRT4OIK+StCOAp69t3EUbFxf75M0C5rezLLRXEAlCvV9ims/CF4vgijKAmq31n/m7HyLKka45uXkCZZtz2PLzsqE5TTs3SPwvOBuoLhUqBa3Cns0eEzs2J+lOC2HHhSlCaABrM6JyZ/Oojhlz+n0z16w6xhH83u4sLi3WyLJpII3cn54L0a8yRbDTYcunsp9dL1eAGdDTBktxkXC+XieuMdxtEzceANDPp2iMTFo5w0qLFmoVEaW78wraF4VL9jZuwfiglqolifpPgbkVyHGeKmAn31A7t9/dzP1nKE8cZuwsYNtYU3DbhxH8QOgzErnCWL2wR2m3w/nQfCA3X+XffBhEUGoEXgDE2IXwW9zcJDKF1u16zZcWPNw7fOH9+/darz3wIDa5Tld55dqAcNR5GQbbbHnh00mvg8FRCOUW0lBM4pix42bLIxCF2SAPLJUKd7lkjxbbVlvNaUSc6VAL+5tODljjp8Ad+h814FbzNhUQ0329iH/x6dGlj3x4ggXSJBZrF5fX/OlmeVQmJvscC0QpZAQBS8dNy74o1UlubGcaNlksTe6LzL6X2VS7Z13mTRbMRhPv1sH1u9EbvirTt5pYzRPA1xulaJzy+ONgVuLSbEkrmdvxRZmIGPrLB08OCigStAVxkkU4naQ24ZWzRdQoNvt1NUB4ErPVwc3aTpLmtWq7YRgw6vbX8RC6KbVcDatPgJZNZ6HqT91K040faQIiqCiISRpeVpwk2llVIAVQq4O1tszrgbvyXhBPrq424tx6faGam+xlVXfWvp59U6GHYpvJ3z2ttpkkqHRTgTHXVT3CMvW7zeEN7D9FZ7CZB+mrshQroEUIH0vkLXbTeTWpe5V+hB3h7tL2sO9K1p6Wvju8jha0dsCgFXr+MMsvUcwRVDBE64eQ3odkOUwfLlcCktFiGKvKouiSLeT9KqcWekNo32c3hDqtaP6IVNk4ah2pLYPBVmp1+pMUYS6qshMZUpNUNajo7aKK1ZBkZQjoF9o1FSF4U/GrNIGnajWjmhC3ZFhSGwlMZJwdCjhea1AqQuSKksbA+jdwt+t9N5ENW2fK5vA7EgqVGK2NcPkaJ7SjqU0P0bFY4H3iauDatln2KvU2vwbxjH5UKiJZCbDze9hXaq3MWwIh0dHdcxKgnTUgB/cyzYo6jJ2ZSquibc0GG44MVyLK8Tz78tXsrRzsdFo/KKLr3dFlttQyWMqy0xuMKmxfsLwqE3fKiX1kCzjCxLI6LstS8UCJqQdGQ2P2vS9EbQmI/Gk5Ff3h2C5v+9AuaQJ6uTa9261ODuazvzAjXt8m77f6qwgiJYf87k0nhd7BM5z49qTO+bHyaqo8zN6qaLTlDpCilcgbbJpuTsw+I54u4iTzxy7ytctnrvYWs7JxoLsGM7C7BIdt1bjHRtvADPprlI3TDZOkaG8eXB63qHar3F9Zy6657bpvPgfGThZlw==)

**Comment by yue1123** [comment]
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/97fa8197-7c6f-4ca0-9e79-1fea317ad2c2">
训练场使用的 cdn 资源并非最新的。请通过我提供的 playground 链接查看2.3.5 的效果。

**Comment by 3246046194** [comment]
![微信图片_20240808092006](https://github.com/user-attachments/assets/b7893551-49fb-4ef8-bac4-c5d19f5612a7)
啊 我的也是3.5版本，但是和3.4报错一样 我也重启了项目也清空了本地内存还是无济于事

**Comment by 3246046194** [comment]
这个项目以前是2.3.2版本的，3.2有些地方是不是和3.5写法不同呀，如果一样的话，您说按道理不该报错呀，还是我在下载的时候有丢包的情况

**Comment by 3246046194** [comment]
![image](https://github.com/user-attachments/assets/6a435703-a8bf-410a-a435-cc3d2c41543f)
![image](https://github.com/user-attachments/assets/6c9837b7-bf32-464c-92c0-b2a4b5fd52df)
只能用淘宝镜像下载2.3.5

**Comment by yue1123** [comment]
> 这个项目以前是2.3.2版本的，3.2有些地方是不是和3.5写法不同呀，如果一样的话，您说按道理不该报错呀，还是我在下载的时候有丢包的情况

只是小版本不一样，都是兼容更新

**Comment by yue1123** [comment]
你尝试本地创建一个新项目来测试这个问题，你现在的项目有这个错误应该是其他的地方影响

**Comment by 3246046194** [comment]
> 你尝试本地创建一个新项目来测试这个问题，你现在的项目有这个错误应该是其他的地方影响

确实和版本没有关系 我自己新建一个就没事，感谢作者悉心讲解 感谢！！
接下来我就要自己解决啦，辛苦！
