### ISSUE TITLE
请教demo为什么edge能打开 chrome打不开啊？

### ISSUE THREAD

**Issue by ufoozhenghao** [yue1123/vue3-baidu-map-gl#8]
[demo连接](https://yue1123.github.io/vue3-baidu-map-gl/zh/base/#%E5%9F%BA%E7%A1%80%E7%BB%BC%E5%90%88%E7%A4%BA%E4%BE%8B)

mac chrome 版本 103.0.5060.114（正式版本） (x86_64) 
![image](https://user-images.githubusercontent.com/42081344/178641450-3e436120-fbff-4b58-9f78-91672298e1cc.png)

**Comment by yue1123** [comment]
![image](https://user-images.githubusercontent.com/61490799/178642034-7bfcca1f-79eb-414d-8568-17ac0576d6aa.png)
我这windows chrome版本比你低一点, 没这个问题诶

**Comment by ufoozhenghao** [comment]
找到了 设置里开启硬件加速
<img width="729" alt="image" src="https://user-images.githubusercontent.com/42081344/178646905-6f669035-534e-43f0-8102-e35c2b54073f.png">
