### ISSUE TITLE
pluginReady 回调里面第二个参数为undefind

### ISSUE THREAD

**Issue by huxiguo** [yue1123/vue3-baidu-map-gl#89]
**Describe the bug** A clear and concise description of what the bug is.

**To Reproduce** Steps to reproduce the behavior:

**Expected behavior** A clear and concise description of what you expected to happen.

**Screenshots** If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context** Add any other context about the problem here.

pluginReady 回调里面第二个参数为undefind,并且如果有两个页面都注册了动画组件，只有一个页面会回调pluginReady ，另一个页面不会，我使用的是在每个BMap 组件里面注册组件

**Comment by guixianleng** [comment]
正确姿势：
`const getPluginReady = (map, pluginRecord) => {
  console.log(pluginRecord, 'pluginRecord');
}`

**Comment by yue1123** [comment]
能提供一个最小复现demo吗
