### ISSUE TITLE
使用 BMapGL 报未定义，想知道 在哪个回调，或者在哪里使用才可以使用原生的sdk

### ISSUE THREAD

**Issue by wmy94827** [yue1123/vue3-baidu-map-gl#9]
使用 BMapGL 报未定义，想知道 在哪个回调，或者在哪里使用才可以使用原生的sdk

**Comment by yue1123** [comment]
看看这个能不能满足你的需求https://yue1123.github.io/vue3-baidu-map-gl/zh/base/com-events.html

**Comment by imddc** [comment]
> 看看这个能不能满足你的需求https://yue1123.github.io/vue3-baidu-map-gl/zh/base/com-events.html

这个在文档里已经没有了, 有最新的地址吗? 目前是通过一个重试方法来使用`BMapGl`的
