### ISSUE TITLE
你好，我想问下百度地图有滚动条的时候缩放会偏移这个问题你是怎么解决的

### ISSUE THREAD

**Issue by badspider7** [yue1123/vue3-baidu-map-gl#91]
你好，我想问下百度地图有滚动条的时候缩放会偏移这个问题你是怎么解决的？
之前查了一些解决办法都不适用，什么固定住，不要滚动条。
我的应用场景是根据ai的回答来显示地图，每个回答都会有一个地图这样子，但是鼠标滚动放大缩小的时候会根据中心点进行偏移，想看看作者是怎么解决的，谢谢啦

**Comment by badspider7** [comment]
你好，不是的，如果在页面有滚动条的时候，触发地图缩放的时候会产生偏移，没有在中心点进行缩放，而向上或者向下偏移了，好像是因为他缩放拿的整个文档的scrollTop，但是我看这个库好像没有这个影响，我用的原生地图api会有这个问题，所以想问问你

**Comment by yue1123** [comment]
文档中的示例也没做什么特殊处理，你看下Bmap这个组件默认参数吧，参考下，你可能某个参数没设置

**Comment by badspider7** [comment]
好的，谢啦
