### ISSUE TITLE
[Vue3 BaiduMap GL/BMapGL SDK]: Cannot read properties of null (reading 'clear')

### ISSUE THREAD

**Issue by xiongli1997** [yue1123/vue3-baidu-map-gl#92]
在弹窗内加载地图，关闭时销毁会报错[Vue3 BaiduMap GL/BMapGL SDK]: Cannot read properties of null (reading 'clear')

**Comment by yue1123** [comment]
猜测是因为弹窗销毁了弹窗的dom，sdk找不到示例挂载的dom，所以报错了，这个不影响功能吧？

**Comment by xiongli1997** [comment]
> 猜测是因为弹窗销毁了弹窗的dom，sdk找不到示例挂载的dom，所以报错了，这个不影响功能吧？

目前还没发现有什么影响
