### ISSUE TITLE
你好，这个不用了怎么销毁呢

### ISSUE THREAD

**Issue by badspider7** [yue1123/vue3-baidu-map-gl#93]
你好，这个库很好用，提高了很多效率，给一大大的好评❤️。
但是有个问题我通过 initd这个事件拿到 map, BmapGL, instance ，这三个都没有看到有distory方法欸，想知道是直接拿到dom删掉就可以了吗，那一些事件也会同时注销掉吗。

**Comment by badspider7** [comment]
因为我一个页面可能有多个实例这样子，不销毁的话内存占用有点大

**Comment by yue1123** [comment]
组件内部是做了在逐渐卸载时的map实例销毁，你只需要控制好组件的销毁即可

**Comment by badspider7** [comment]
ok，哈哈哈回复的好快

**Comment by yue1123** [comment]
🤣刚好看到

**Comment by badspider7** [comment]
刚刚看了下，也可以通过组件暴露出来的getMapInstance方法拿到map，然后调用map.distory()

**Comment by clearlovehuan** [comment]
如果我想重新渲染地图，但是聚合点和多边形什么的还是不变，这种要怎么弄

**Comment by yue1123** [comment]
你找找百度地图有没有相关api吧，没有就做一个组件局部刷新就好了
