### ISSUE TITLE
我用document.body.style.zoom调整分辨率之后，会出现一些元素错位的问题，比如绘制圆的中心点或者某些下拉框，像这种情况有什么办法能解决么

### ISSUE THREAD

**Issue by clearlovehuan** [yue1123/vue3-baidu-map-gl#94]
**Describe the bug** A clear and concise description of what the bug is.

**To Reproduce** Steps to reproduce the behavior:

**Expected behavior** A clear and concise description of what you expected to happen.

**Screenshots** If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context** Add any other context about the problem here.

**Comment by yue1123** [comment]
没有遇到过这种情况。
