### ISSUE TITLE
大神在使用 BControl 时，如果里面有滚动条得话，滚动只能缩放地图

### ISSUE THREAD

**Issue by syb990597617** [yue1123/vue3-baidu-map-gl#95]

**Comment by syb990597617** [comment]
还有一个问题就是使用 BMarker 自定义图标 imageUrl 无法获取到本地得资源

**Comment by yue1123** [comment]
没太明白，BControl 是自定义控件，和滚动有什么关系呢，有视频演示之类的吗？

**Comment by syb990597617** [comment]
就是自定义控件里面有个 table ，table 里面有垂直的滚动条，在用鼠标中间键滚动时滚动条不起作用，只能触发缩放地图效果

> 没太明白，BControl 是自定义控件，和滚动有什么关系呢，有视频演示之类的吗？

**Comment by yue1123** [comment]
监听鼠标滚轮事件，阻止冒泡试试
