### ISSUE TITLE
能通过API方式添加marker嘛

### ISSUE THREAD

**Issue by zhuqiyun** [yue1123/vue3-baidu-map-gl#97]
能通过API方式添加marker嘛

**Comment by yue1123** [comment]
可以的，在initd事件触发后，api的所有方法就都可以访问了

**Comment by zhuqiyun** [comment]
{ map, BmapGL, instance }，用这里面的哪一个？添加一个marker，能大体写一下嘛？我之前直接用api添加没有问题 ，这个不知道怎么用。

**Comment by yue1123** [comment]
请参考百度地图官方文档实例。

**Comment by zhuqiyun** [comment]
> 请参考百度地图官方文档实例。

能指点一下嘛，是要在index中引入sdk嘛，还是不用引入了？直接有现在的map实例？

**Comment by yue1123** [comment]
BMapGL就是API入口了，可以直接用
