### ISSUE TITLE
初始化完毕后，获取的 map, BmapGL, instance 都是undefined

### ISSUE THREAD

**Issue by zhuqiyun** [yue1123/vue3-baidu-map-gl#98]
function handleInitd({ map, BmapGL, instance }: any) {
  pageMap.mapHandle = map
  pageMap.bmapHandle = BmapGL
  console.log('mapHandle------>', pageMap.bmapHandle)
  console.log('BmapGL------>', BmapGL)
  pageMap.mapIns = instance
  getUseAddressGeocoder.get(pageMap.addr, pageMap.city)
}

**Comment by yue1123** [comment]
能提供下完整示例代码吗，包含template
