### ISSUE TITLE
途经点路径规划

### ISSUE THREAD

**Issue by zhuqiyun** [yue1123/vue3-baidu-map-gl#99]
const driving = new BMapGL.DrivingRoute(pageMap.mapHandle, {
    renderOptions: {
      map: pageMap.mapHandle,
      autoViewport: true,
    },
  })
  const start = new BMapGL.Point(116.310791, 40.003419)
  const end = new BMapGL.Point(116.486419, 39.877282)
  const wayPonit = new BMapGL.Point(116.486419, 39.877282)
  driving.search(start, end, { wayPonit: [wayPonit] })

图示不能传入途经点，3.0不能传入途经点，有什么解决方法跟2.0一样可以传入途经点嘛。

**Comment by zhuqiyun** [comment]
DrivingRouteLine这个是可以增加途经点的，但是提示找不到

**Comment by yue1123** [comment]
感谢反馈，这不属于本组件库的能处理的issue 范围。你可以参考下这个示例 https://lbsyun.baidu.com/jsdemo.htm#drivingroute1
